### ISSUE TITLE
SQL查询关闭，但是后台仍然在运行？关于查询的一些问题

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#100]
### 问题描述
1.查询页面关闭，但是后台SQL查询线程还在，没有被Kill，我这边是出现了查询耗时50000秒的情形，存在较大风险。建议查询窗口关闭，后台查询自动中断，并且添加查询超时时间阈值。

2.select *形式查询时，平台不会在查询语句后面加limit限制，即时已经这样设置了；但是如果select具体的字段，limit还是会奏效的。

3.不支持replace into语句及call存储过程，能够提交，但是执行的时候，只会执行use schema,其他的语句将不执行，并且也不再执行列表里展示。

### 版本信息
 - 应用版本/分支：Release v1.4.2 
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
关于 select * 的问题， 在 #56 已提过， 而且在 1.4.3 版本已经修复， 请考虑升级修复这个问题。

查询页面超时的问题， 你说的很对， 确实需要一个有一个超时时间， 目前的查询是同步调用， 所以要设置超时时间， 需要把同步请求改成异步， 然后设置计时器， 杀死超时任务等， 这个做起来应该不算特别费时间

关于replace into和存储过程， 由于工单执行是深度依赖inception和pt-osc , 这些问题大概率是这两个工具的问题， 你可以尝试把inception里的pt-osc选项关掉重试
```
inception_osc_on=OFF
```
如果关掉还不行的话， 就有可能是inception的限制。 如果inception有这些硬限制的话， 应该短期内无法修复。

**Comment by hhyo** [comment]
查询主动kill也可以考虑加上，我现在是部署的kill脚步定时跑（比较low）
关闭或者修改页面主动kill这个，emmm，得查下判断方法
改成异步的话，结果展现用websocket交互？

**Comment by LeoQuote** [comment]
可以暂时做一个假异步，在view里等待异步请求返回，在这里做timeout

**Comment by thickhang** [comment]
您好，请问我在手动安装1.4.5版本时候，报这个错误，怎么解决呢，谢谢答疑。

(venv4archery) [root@localhost Archery-1.4.5]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 235, in __init__
    self.set_character_set(charset)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 358, in set_character_set
    super(Connection, self).set_character_set(charset)
_mysql_exceptions.OperationalError: (2019, "Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/migrations/loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 235, in __init__
    self.set_character_set(charset)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 358, in set_character_set
    super(Connection, self).set_character_set(charset)
django.db.utils.OperationalError: (2019, "Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)")

发送自 Windows 10 版邮件应用

发件人: Leo Q
发送时间: 2019年4月3日 17:54
收件人: hhyo/Archery
抄送: thickhang; Author
主题: Re: [hhyo/Archery] SQL查询关闭，但是后台仍然在运行？关于查询的一些问题 (#100)

关于 select * 的问题， 在 #56 已提过， 而且在 1.4.3 版本已经修复， 请考虑升级修复这个问题。
查询页面超时的问题， 你说的很对， 确实需要一个有一个超时时间， 目前的查询是同步调用， 所以要设置超时时间， 需要把同步请求改成异步， 然后设置计时器， 杀死超时任务等， 这个做起来应该不算特别费时间
关于replace into和存储过程， 由于工单执行是深度依赖inception和pt-osc , 这些问题大概率是这两个工具的问题， 你可以尝试把inception里的pt-osc选项关掉重试
inception_osc_on=OFF
如果关掉还不行的话， 就有可能是inception的限制。 如果inception有这些硬限制的话， 应该短期内无法修复。

**Comment by LeoQuote** [comment]
和本issue不相关的问题请另开issue

**Comment by hhyo** [comment]
查询终止的问题还没处理

**Comment by LeoQuote** [comment]
查到有一个cached参数，可以让djangoQ在缓存中查询结果，我觉得可以考虑这个做。
