### ISSUE TITLE
问题咨询：MongoDB执行工单报错，不知道哪里的问题，还请各位大神帮忙看下，谢谢

### ISSUE THREAD

**Issue by zt901** [hhyo/Archery#1012]
### 问题描述
执行MongoDB工单报错，报错信息如下：
local variable 'msg' referenced before assignment : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/opt/Archery-1.8.0/sql/utils/execute_sql.py", line 35, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/opt/Archery-1.8.0/sql/engines/mongo.py", line 319, in execute_workflow
return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
File "/opt/Archery-1.8.0/sql/engines/mongo.py", line 323, in execute
self.get_master()
File "/opt/Archery-1.8.0/sql/engines/mongo.py", line 283, in get_master
master = self.exec_cmd(sql)
File "/opt/Archery-1.8.0/sql/engines/mongo.py", line 277, in exec_cmd
return msg
UnboundLocalError: local variable 'msg' referenced before assignment

### 版本信息
 - 应用版本/分支：v1.8.0
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
检查一下实例配置, 用户密码, 主机名和端口号有填吗? 不过这个报错也是有些迷惑, 后续要改一下

**Comment by zt901** [comment]
我怀疑是：MongoDB没有开启权限认证，添加实例的时候没有输入用户名密码导致的；但是，没开启权限认证的情况下不输入用户名密码是可以连接成功的；

sql/engines/mongo.py文件中258行：if self.user and self.password and self.port and self.host
如果MongoDB没有用户名密码，是不是这个判断为false，从而没有进入这个if的代码块，导致msg没定义就 return msg了？

**Comment by LeoQuote** [comment]
你说的没错, 能不能开启一下认证, 然后填写一下用户密码看看?

**Comment by zt901** [comment]
好的，我先开启mongo认证试一下，感谢回复

**Comment by RankRao** [comment]
我也有这个问题，mongo没有使用密码认证。在Archery平台上，可以正常进行查询，但是在上线审核的时候，就报错误：UnboundLocalError: local variable 'msg' referenced before assignment
