### ISSUE TITLE
[ 问题咨询 ]在线查询报错：无法校验查询语句权限，请联系管理员，错误信息：connect() argument 1 must be str, not None

### ISSUE THREAD

**Issue by jiaping0424** [hhyo/Archery#1027]
### 问题描述

用户U1属于资源组1，实例1也属于资源组1，用户U1已经申请了访问table1的查询权限，但在查询时报错：无法校验查询语句权限，请联系管理员，错误信息：connect() argument 1 must be str, not None

我尝试了申请数据库级权限和表级权限，但都报错，docker archery日志显示如下：
[2021-02-08 19:04:07,589][ThreadPoolExecutor-0_0:140679409395456][task_id:default][query_privileges.py:85][ERROR]- 无法校验查询语句权限，实例1
，select * from schema1.table1
，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 409, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 147, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
  File "/opt/archery/sql/engines/goinception.py", line 116, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 35, in get_connection
    self.conn = MySQLdb.connect(host=go_inception_host, port=go_inception_port, charset='utf8mb4',
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: connect() argument 1 must be str, not None

[2021-02-08 19:05:46,320][ThreadPoolExecutor-0_0:140679409395456][task_id:default][query_privileges.py:85][ERROR]- 无法校验查询语句权限，实例1
，select * from t_bak_01，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 409, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 147, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
  File "/opt/archery/sql/engines/goinception.py", line 116, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 35, in get_connection
    self.conn = MySQLdb.connect(host=go_inception_host, port=go_inception_port, charset='utf8mb4',
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: connect() argument 1 must be str, not None

### 版本信息
 - 应用版本/分支：Release v1.8.0  
 - 部署方式：Docker部署

在常见问题里没找到有类似的问题，请帮分析一下，感谢！

**Comment by jiaping0424** [comment]
但是我用管理员账号是可以执行查询的。

**Comment by jiaping0424** [comment]
上面报错的是MYSQL数据库，申请ORACLE数据库的权限后查询无报错。

**Comment by jiaping0424** [comment]
已经解决了，在“配置项管理”里加入地址即可，我配置了如下4项：
GO_INCEPTION_HOST 172.18.0.4  // 这个地址是goinception 容器的地址
GO_INCEPTION_PORT 4000   // 这个端口是goinception 容器的端口
REMOTE_BACKUP_HOST 172.18.0.4  // 这个地址是goinception 容器的地址
REMOTE_BACKUP_PORT  4000   // 这个端口是goinception 容器的端口
填写完以后点击右上角的“连接测试”，页面会提示：goInception和备份库测试连接成功，请点击页面下方的保存按钮生效！
然后再查询就不报错了！
