### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/Archery#1040]
### 问题描述
gh-ost执行时，查看进度条无任何数据，archery.log报错日志如下：

[WARNING]- goInception语句执行报错，错误信息Traceback (most recent call last):
  File "/root/Archery-1.8.0/sql/engines/goinception.py", line 119, in query
    effect_row = cursor.execute(sql)
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

### 版本信息
 - 应用版本/分支：Release v1.8  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
连接不上goInception，可以看下对应的日志
