### ISSUE TITLE
[ 问题咨询 ]数据库启用的ssl，无法连接

### ISSUE THREAD

**Issue by qingjian-meng** [hhyo/Archery#1083]
### 问题描述
我后端的数据库强制启用了ssl，第一次登陆，无法连接

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker、手工部署

### 启动错误日志
archery.log
```
[2021-05-05 21:05:27,081][MainThread:140236916401984][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(9002, 'SSL connection is required. Please specify SSL options and retry.')Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/common/config.py", line 25, in get_all_config
    for items in all_config:
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 111, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

[2021-05-05 21:05:32,400][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:05:49,727][MainThread:140236916401984][task_id:default][config.py:33][ERROR]- 获取系统配置信息失败:(9002, 'SSL connection is required. Please specify SSL options and retry.')Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/common/config.py", line 25, in get_all_config
    for items in all_config:
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 111, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

[2021-05-05 21:05:49,915][MainThread:140236916401984][task_id:default][auth.py:72][ERROR]- 验证用户密码时报错
[2021-05-05 21:05:49,918][MainThread:140236916401984][task_id:default][auth.py:73][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/archery/common/auth.py", line 61, in authenticate
    user = Users.objects.get(username=username)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

[2021-05-05 21:06:06,922][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:06:41,782][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:07:16,325][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:07:50,592][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:08:24,793][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:09:00,333][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:09:34,584][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:10:08,469][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:10:43,292][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:11:17,757][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:11:55,133][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:12:29,563][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:13:03,505][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:13:37,537][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:14:11,463][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:14:45,972][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:15:19,949][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:15:54,192][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:16:28,207][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:17:02,258][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:17:36,771][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:18:11,189][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:18:45,438][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:19:19,626][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:19:54,563][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:20:29,035][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:21:03,932][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:21:38,189][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:22:13,103][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:22:47,015][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:23:21,312][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:23:56,260][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:24:31,134][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:25:05,294][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:25:41,867][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:26:16,198][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:26:51,156][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:27:25,964][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:28:00,461][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:28:37,713][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:29:12,452][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:29:46,751][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:30:20,591][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:30:55,243][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:31:30,476][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:32:07,693][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:32:43,128][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:33:17,999][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:33:54,380][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:34:28,117][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:35:01,980][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:35:36,523][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:36:10,793][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:36:44,779][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:37:19,576][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')
[2021-05-05 21:37:53,618][MainThread:140427164346176][task_id:django-q][cluster.py:663][ERROR]- (9002, 'SSL connection is required. Please specify SSL options and retry.')

```

**Comment by hhyo** [comment]
#918

**Comment by qingjian-meng** [comment]
现有的是添加数据库强制开启了SSL，这个报错是设置后台数据库的时候发生，我解决办法是在setting.py里面加了证书配置
```
# 该项目本身的mysql数据库地址
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xxx',
        'USER': 'x',xx
        'PASSWORD': '***',
        'HOST': 'xxxxx',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'ssl': {'ca':'/opt/archery/my.pem'}
        },
        'TEST': {
            'NAME': 'test_archery',
            'CHARSET': 'utf8mb4',
        },
    }
}
```
