### ISSUE TITLE
[ 问题咨询 ]工单流程邮件通知的时候，工单提交，和审核都有通知，工单完成没有通知

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#1092]
### 问题描述
工单流程邮件通知的时候，工单提交，和审核都有通知，工单完成没有通知。查看日志有报错。

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：手工部署

日志：
[2021-05-17 18:16:52,054][MainThread:140356109981504][task_id:default][sendmsg.py:124][ERROR]- 邮件推送失败
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/local/python3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/archery/archery-1.8.1/common/utils/sendmsg.py", line 118, in send_email
    server.sendmail(self.MAIL_REVIEW_FROM_ADDR, to + list_cc, main_msg.as_string())
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 872, in sendmail
    (code, resp) = self.rcpt(each, rcpt_options)
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 543, in rcpt
    return self.getreply()
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out

邮箱配置：
没有填邮箱密码MAIL_SMTP_PASSWORD，其他正常填写。测试连接没问题。

**Comment by gaoqiang-0327** [comment]
![image](https://user-images.githubusercontent.com/59639792/118474679-e652b480-b73d-11eb-8fd0-5916c8d86b04.png)

**Comment by gaoqiang-0327** [comment]
问题已解决，非常感谢。
