### ISSUE TITLE
[ bug ] mysql部分DML没有备份成功

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/Archery#1100]
### 截图
![image](https://user-images.githubusercontent.com/40595864/119319338-e5c19d00-bcac-11eb-840e-85feb05b081d.png)

 
### 错误日志
[2021-05-24 16:25:34,283][MainThread:140135671969600][task_id:django-q][cluster.py:390][ERROR]- Failed [sqlreview-pass-122] - 'NoneType' object has no attribute 'values' : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/opt/archery/sql/notify.py", line 213, in notify_for_audit
    __send(msg_title, msg_content, msg_to, msg_cc, feishu_webhook=feishu_webhook, dingding_webhook=dingding_webhook,
  File "/opt/archery/sql/notify.py", line 69, in __send
    msg_sender.send_feishu_user(msg_title, msg_content, open_id, user_mail)
  File "/opt/archery/common/utils/sendmsg.py", line 239, in send_feishu_user
    open_id = open_id + get_feishu_open_id(user_mail)
  File "/opt/archery/common/utils/feishu_api.py", line 49, in get_feishu_open_id
    for key in resp.get('data').get('email_users').values():
AttributeError: 'NoneType' object has no attribute 'values'

[2021-05-24 16:25:44,161][MainThread:140135671969600][task_id:django-q][signals.py:28][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [sqlreview-execute-122] because 'NoneType' object has no attribute 'values'

### 版本信息
应用版本/分支：1.8.1

部署方式：Docker

**Comment by hhyo** [comment]
影响行数为0，也就不需要备份

**Comment by michael-liumh** [comment]
确实是，谢谢了
