### ISSUE TITLE
[ 问题咨询 ]-备份就报错-不备份数据就成功执行

### ISSUE THREAD

**Issue by 2963305366** [hhyo/Archery#111]
### 问题描述
1: 提交SQL选择需要备份的时候就会在/opt/software/downloads/log/archery.log 打印一个报错，然后工单状态一直是：执行中，确认中...
2：如果提交的SQL不需要备份，则不会报错。系统管理-配置项管理-点击测试Inception连接，又是成功的。备份用户的授权都是 grant ALL PRIVILEGES ON *.*  

报错内容如下：
[2019-04-09 14:58:34,751][MainThread:140615233382208][task_id:django-q][cluster.py:305][DEBUG]- queueing from django_q:archery:q
[2019-04-09 14:58:34,752][MainThread:140615233382208][task_id:django-q][cluster.py:356][INFO]- Process-1:4 processing [nitrogen-london-golf-minnesota]
[2019-04-09 14:58:45,317][MainThread:140615233382208][task_id:django-q][signals.py:26][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [nitrogen-london-golf-minnesota] because local variable 'execute_result' referenced before assignment
[2019-04-09 14:58:45,317][MainThread:140615233382208][task_id:django-q][cluster.py:336][ERROR]- Failed [nitrogen-london-golf-minnesota] - '<' not supported between instances of 'NoneType' and 'int' : Traceback (most recent call last):
  File "/root/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/software/Archery-1.4.3/sql/utils/execute_sql.py", line 29, in execute
    return execute_engine.execute_workflow()
  File "/opt/software/Archery-1.4.3/sql/engines/mysql.py", line 245, in execute_workflow
    one_line_execute_result = inception_engine.query(sql=sql_execute)
  File "/opt/software/Archery-1.4.3/sql/engines/inception.py", line 40, in query
    effect_row = cursor.execute(sql)
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 253, in execute
    self._warning_check()
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 148, in _warning_check
    warnings = db.show_warnings()
  File "/root/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 379, in show_warnings
    if self._server_version < (4,1): return ()
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### 版本信息
 - 应用版本/分支：Release v1.4.3 
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
inception有问题，推荐使用hhyo更改后的inception https://github.com/hhyo/inception

**Comment by hhyo** [comment]
升级Release v1.4.5，异常也会记录到前台显示

如果不想使用推荐的inception版本，可以直接按照这里的方式修改
https://github.com/hhyo/archery/wiki/FAQ#must-start-as-begin-statement
