### ISSUE TITLE
[ bug ] redis执行 smembers 命令报错

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#1156]
### 重现步骤

1. SQL查询-在线查询（redis实例），
2. 执行命令  smembers  XXXXXXX
3. 跳框提示  Internal Server Error

### 期待结果和实际结果
期待结果：
        查询结果为 []
实际结果:
        跳框提示  Internal Server Error

### 错误日志
```
[2021-08-10 15:03:25,928][MainThread:140142995646272][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/utils/extend_json_encoder.py", line 54, in default
    return convert(obj)
  File "/usr/local/python3/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 11, in convert
    raise TypeError('can not convert type')
TypeError: can not convert type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/query.py", line 175, in query
    return HttpResponse(json.dumps(result, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 56, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type set is not JSON serializable
```

### 版本信息
应用版本/分支：v1.8.1

部署方式：Docker

个人分析:
        应该是这个命令查询结果为 []  ，然后这边直接做 json 解析失败造成的

**Comment by czxin788** [comment]
![image](https://user-images.githubusercontent.com/13861904/129994771-64a9a172-2ca1-4d5f-831c-155c8ded87f5.png)

**Comment by kunphp** [comment]
最新版已兼容set类型了，https://github.com/hhyo/Archery/blob/master/common/utils/extend_json_encoder.py
![image](https://user-images.githubusercontent.com/26486702/134630770-1706ae4e-dfc3-46c8-9987-affc2ca3d83f.png)
可以手动加上去就好了

**Comment by ghost** [comment]
已解决，多谢
