### ISSUE TITLE
手动部署1.4.5版本 在初始化数据库时报错

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#116]
### 问题描述
1.mysql,inception,redis,mongo,nginx是不是都是自己安装部署？
2.在初始化数据库，时候，报错。
```
(venv4archery) [root@localhost Archery-1.4.5]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 235, in __init__
    self.set_character_set(charset)
  File "/home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 358, in set_character_set
    super(Connection, self).set_character_set(charset)
_mysql_exceptions.OperationalError: (2019, "Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)")

The above exception was the direct cause of the following exception:
```

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
部署前所有的依赖都需要准备完毕而且正常运行，你是不是没有启动mysql？

**Comment by thickhang** [comment]
刚刚这个问题我解决了，字符集好像只能设为UTF8，不能设置为UTF8MB4。
但是我在执行
# 编译翻译文件
python3 manage.py compilemessages
这一步骤时，报以下错误日志。怎么处理呢？

Execution of msgfmt failed: /home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/wtforms/locale/ca/LC_MESSAGES/wtforms.po:48: a format specification for argument 'max' doesn't exist in 'msgstr'
msgfmt: found 1 fatal error
Execution of msgfmt failed: /home/archer/Archery-1.4.5/venv4archery/lib/python3.6/site-packages/wtforms/locale/ar/LC_MESSAGES/wtforms.po:57: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
msgfmt: found 1 fatal error

**Comment by LeoQuote** [comment]
这个编译翻译文件时出现的错误可以无视。 

我建议你把虚拟环境挪到项目文件外部，可以规避这个错误。
