### ISSUE TITLE
[ 问题咨询 ]选择备份偶尔执行异常导致备份失败，实际上SQL语句已经上线成功

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#121]
问题描述 
 提交SQL选择需要备份的时候偶尔会打印执行异常信息
```
 (2013, 'Lost connection to MySQL server during query') : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/opt/archery/sql/utils/execute_sql.py", line 27, in execute
return execute_engine.execute_workflow()
File "/opt/archery/sql/engines/mysql.py", line 240, in execute_workflow
one_line_execute_result = inception_engine.query(sql=sql_execute)
File "/opt/archery/sql/engines/inception.py", line 40, in query
effect_row = cursor.execute(sql)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
self.errorhandler(self, exc, value)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
raise errorvalue
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
res = self._query(query)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
rowcount = self._do_query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
db.query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
_mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

版本信息
应用版本/分支：Release v1.4.5
部署方式：docker部署

**Comment by LeoQuote** [comment]
你这个报错信息好奇怪啊, 为什么好好的python3.6 里面又是 3 6 又是 3. 6 的
能不能麻烦你提供一个容易看的版本? 这个看起来好难啊

**Comment by lijie861221** [comment]
> 你这个报错信息好奇怪啊, 为什么好好的python3.6 里面又是 3 6 又是 3. 6 的
> 能不能麻烦你提供一个容易看的版本? 这个看起来好难啊

是3.6，用手机ocr识别的，有些少了点。。。

**Comment by LeoQuote** [comment]
可能你有什么难言之隐不能直接复制粘贴吧.....
anyway你可以看一下``admin``页面里的``django_q`` 区域的 ``failed_tasks`` 里有没有一些日志吗?
还有后台的日志:

```
/downloads/log/archery.log
/downloads/log/qcluster.log
/downloads/log/soar.log
docker logs archery -f --tail=10
```

这些信息提供一下, 另外这种手机拍照依然很难看清, 麻烦你下次回复的时候直接复制粘贴文本, 这样有助于问题的解决.

**Comment by lijie861221** [comment]
> 可能你有什么难言之隐不能直接复制粘贴吧.....
> anyway你可以看一下`admin`页面里的`django_q` 区域的 `failed_tasks` 里有没有一些日志吗?
> 还有后台的日志:
> 
> ```
> /downloads/log/archery.log
> /downloads/log/qcluster.log
> /downloads/log/soar.log
> docker logs archery -f --tail=10
> ```
> 这些信息提供一下, 另外这种手机拍照依然很难看清, 麻烦你下次回复的时候直接复制粘贴文本, 这样有助于问题的解决.

[logs.txt](https://github.com/hhyo/Archery/files/3069293/logs.txt)
[qcluster.log](https://github.com/hhyo/Archery/files/3069294/qcluster.log)
[archery.log](https://github.com/hhyo/Archery/files/3069297/archery.log)

**Comment by lijie861221** [comment]
> 可能你有什么难言之隐不能直接复制粘贴吧.....
> anyway你可以看一下`admin`页面里的`django_q` 区域的 `failed_tasks` 里有没有一些日志吗?
> 还有后台的日志:
> 
> ```
> /downloads/log/archery.log
> /downloads/log/qcluster.log
> /downloads/log/soar.log
> docker logs archery -f --tail=10
> ```
> 这些信息提供一下, 另外这种手机拍照依然很难看清, 麻烦你下次回复的时候直接复制粘贴文本, 这样有助于问题的解决.

`django_q` 区域的 `failed_tasks`   中
`name`:alaska-twelve-kitten-kansas
`func`:sql.utils.execute_sql.execure
`hook`:sql.utils.execute_sql.execute_callback
`args`:66
`kwargs`:{} 
`result`:(2013, 'Lost connection to MySQL server during query') : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/opt/archery/sql/utils/execute_sql.py", line 27, in execute
return execute_engine.execute_workflow()
File "/opt/archery/sql/engines/mysql.py", line 240, in execute_workflow
one_line_execute_result = inception_engine.query(sql=sql_execute)
File "/opt/archery/sql/engines/inception.py", line 40, in query
effect_row = cursor.execute(sql)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
self.errorhandler(self, exc, value)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
raise errorvalue
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
res = self._query(query)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
rowcount = self._do_query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
db.query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
_mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by hhyo** [comment]
看起来是inception挂了，可以查看下inception的日志 `docker logs inception` 

上面的日志文件中查看回滚语句时，数据库是none，也许inception生成备份库名失败了，请提供执行和备份的mysql实例版本(其实最需要连接名和库名，不过这会涉及数据隐私)，如果你可以使用脱敏后的信息模拟一个能复现的测试步骤最好不过，这个问题可能比较难处理，所以我们需要更多信息


能否尝试在演示环境复现该问题？同时提交时请注意隐私保护，感谢反馈

**Comment by lijie861221** [comment]
> 看起来是inception挂了，可以查看下inception的日志 `docker logs inception`
> 
> 上面的日志文件中查看回滚语句时，数据库是none，也许inception生成备份库名失败了，请提供执行和备份的mysql实例版本(其实最需要连接名和库名，不过这会涉及数据隐私)，如果你可以使用脱敏后的信息模拟一个能复现的测试步骤最好不过，这个问题可能比较难处理，所以我们需要更多信息
> 
> 能否尝试在演示环境复现该问题？同时提交时请注意隐私保护，感谢反馈

谢谢！
inception确实挂了。尝试了几次，问题复现不了。
先关闭了，问题再现了再提。
