### ISSUE TITLE
[ 问题咨询 ]68条insert语句执行报错，但是却已经插入到数据库里面了

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#147]
### 问题描述
在archery里面提交了68条insert语句，在执行时却报执行异常，可实际上数据已经插入成功了，请问是怎么回事，应该怎么解决。

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

###报错信息：
![image](https://user-images.githubusercontent.com/13861904/56628113-2a684d80-667b-11e9-80c9-8f2ababc5cf9.png)
![image](https://user-images.githubusercontent.com/13861904/56628152-4966df80-667b-11e9-9d77-b9aaf11abea0.png)
文本：
(2013, 'Lost connection to MySQL server during query') : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/opt/archery/sql/utils/execute_sql.py", line 27, in execute
return execute_engine.execute_workflow()
File "/opt/archery/sql/engines/mysql.py", line 240, in execute_workflow
one_line_execute_result = inception_engine.query(sql=sql_execute)
File "/opt/archery/sql/engines/inception.py", line 40, in query
effect_row = cursor.execute(sql)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
self.errorhandler(self, exc, value)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
raise errorvalue
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
res = self._query(query)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
rowcount = self._do_query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
db.query(q)
File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
_mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

回滚sql里面也没语句：
![image](https://user-images.githubusercontent.com/13861904/56628192-71eed980-667b-11e9-8e98-6d99716d92fc.png)

inception的报错信息
[root@archery ~]# docker logs inception -f --tail=500
2019-04-12 14:33:37 0 [Note] Welcome to use 2.1.52.1
2019-04-12 14:33:37 6 [Note] Server hostname (bind-address): '*'; port: 6669
2019-04-12 14:33:37 6 [Note] IPv6 is available.
2019-04-12 14:33:37 6 [Note]   - '::' resolves to '::';
2019-04-12 14:33:37 6 [Note] Server socket created on IP: '::'.
/bin/sh: line 1:     6 Bus error               (core dumped) nohup /opt/inception/debug/mysql/bin/Inception --defaults-file=/etc/inc.cnf
2019-04-24 10:03:08 0 [Note] Welcome to use 2.1.52.1
2019-04-24 10:03:08 6 [Note] Server hostname (bind-address): '*'; port: 6669
2019-04-24 10:03:08 6 [Note] IPv6 is available.
2019-04-24 10:03:08 6 [Note]   - '::' resolves to '::';
2019-04-24 10:03:08 6 [Note] Server socket created on IP: '::'.

**Comment by hhyo** [comment]
看Inception日志是执行时Inception挂了，由于Inception停止维护，目前关于Inception的问题没有办法可以处理，所以在v1.5.2中审核执行模块可以切换为goInception，可以尝试升级
https://github.com/hhyo/Archery/releases/tag/v1.5.2

**Comment by czxin788** [comment]
好的，感谢，我准备升级试一下。
不过我有个问题再咨询一下，就是我是docker部署的archery，不知道怎么看当前archery的版本号。

**Comment by hhyo** [comment]
登录页面
![image](https://user-images.githubusercontent.com/8842982/56628948-5df8a700-667e-11e9-9d69-5e138690cc45.png)

**Comment by czxin788** [comment]
谢谢

**Comment by LeoQuote** [comment]
版本可以考虑放在base模版的footer里🤔 类似Jenkins那种
