### ISSUE TITLE
[ 问题咨询 ]查询数据返回 Error 'utf-8' codec can't decode byte 0xed in position 6: invalid continuation byte

### ISSUE THREAD

**Issue by jy3792397** [hhyo/Archery#158]
### 问题描述
查询数据返回 Error 'utf-8' codec can't decode byte 0xed in position 6: invalid continuation byte

![archery_error](https://user-images.githubusercontent.com/6747454/56945888-33658d00-6b5b-11e9-9a9f-ee56a076fb2d.png)

**我的数据表是utf8mb4的**，猜测程序用的utf8，无法解码

日志：
  effect_row = cursor.execute(sql)
ERROR:default:Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 82, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 413, in _query
    self._post_get_result()
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 417, in _post_get_result
    self._rows = self._fetch_row(0)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 385, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 231, in string_decoder
    return s.decode(db.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 6: invalid continuation byte

### 版本信息
 - 应用版本/分支：Release v1.4.2  
 - 部署方式：Docker

**Comment by hhyo** [comment]
测试目前的版本查询含有emoji的数据，会返回?而不是报错，希望可以提供可复现的数据，谢谢

**Comment by LeoQuote** [comment]
字符串是不是可以考虑放在实例配置里？ 或者有没有自动探测的方式？

**Comment by LeoQuote** [comment]
研究了一下数据库和表都可以独立设置编码，要设置还是挺麻烦，自动探测编码也没有搜到相关的内容。

如果uft8mb4可以覆盖大部分需求感觉似乎没必要再做别的了。

**Comment by hhyo** [comment]
嗯，mysql8.0默认字符集也是utf8mb4可

**Comment by LeoQuote** [comment]
master分支已修复， 等待下一次release更新代码即可。
