### ISSUE TITLE
[ 问题咨询 ] SQL慢日志问题

### ISSUE THREAD

**Issue by cai823294620** [hhyo/Archery#163]
### 点击慢查日志时，出现如下报错。
![image](https://user-images.githubusercontent.com/44595276/57187372-1dbbe300-6f20-11e9-99e3-02c5cac5def1.png)

### 报错提示
`archery.mysql_slow_query_review doesn't exist` 创建此表的SQL语句可以分享一下嘛

**Comment by cai823294620** [comment]
### 报错信息如下
```
[2019-05-05 10:28:49,862][MainThread:139907702163264][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 76, in slowquery_review
    slow_sql_count = slowsql_obj.count()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 387, in count
    return self.query.get_count(using=self.db)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 491, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 476, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review' doesn't exist")
```

**Comment by hhyo** [comment]
![image](https://user-images.githubusercontent.com/8842982/57187454-9e2f1380-6f21-11e9-8d9e-3d5f0b236e0b.png)
![image](https://user-images.githubusercontent.com/8842982/57187458-b2731080-6f21-11e9-9371-13bf37eebf0f.png)

**Comment by LeoQuote** [comment]
请查阅文档中的slow query文档，进行一些设置 https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#slowquery

**Comment by cai823294620** [comment]
我明明在数据库内创建了这个表。但它一直提示这个表不存在。

注：在docker-compose中启动的数据库进行了表的创建

**Comment by LeoQuote** [comment]
你具体的建表语句是文档中提供的建表语句吗？ 我们文档中提供了一个慢查询表的创建语句。

**Comment by cai823294620** [comment]
使用docker-compose重新启动了一下。问题解决。我第一次启动的时候，忘记用的哪台主机的mysql了。谢谢

**Comment by mawenbin666** [comment]
> 请查阅文档中的slow query文档，进行一些设置 https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#slowquery

您好，我进行配置了，但还是没有效果哦，您可以帮我看下吗，我的配置信息如下
![image](https://user-images.githubusercontent.com/22042460/59414632-72daf680-8df4-11e9-8815-9b8a92790f6b.png)

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/59415454-1e387b00-8df6-11e9-85c8-81589eb9cae7.png)

我的正常

**Comment by 007mawenbin** [comment]
> ![图片](https://user-images.githubusercontent.com/35367394/59415454-1e387b00-8df6-11e9-85c8-81589eb9cae7.png)
> 
> 我的正常

兄弟，可以帮我看下不，我qq，578410927
