### ISSUE TITLE
[ bug ] 1.5.3 版本不能检测 inception

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#172]
### 重现步骤
部署好1.5.3 版本后，在配置里面配置好后，点击 "测试inception连接"，报错。
![image](https://user-images.githubusercontent.com/35367394/57218790-cb1a1e00-7028-11e9-8164-b2d8d1b1bf6f.png)

### 期待结果和实际结果
期待结果：
![image](https://user-images.githubusercontent.com/35367394/57218816-dcfbc100-7028-11e9-8dbd-391902a65b6d.png)

实际结果:
![image](https://user-images.githubusercontent.com/35367394/57218834-e9801980-7028-11e9-9144-7c9104055a0b.png)

### 截图
![image](https://user-images.githubusercontent.com/35367394/57218847-f3098180-7028-11e9-93e7-3e933cb20bb2.png)

### 错误日志
```
[2019-05-06 18:00:24,148][MainThread:140519739692864][task_id:default][check.py:32][ERROR]- Traceback (most recent call last):
  File "/opt/dba/archery_1.5.3/common/check.py", line 29, in inception
    conn = pymysql.connect(host=inception_host, port=int(inception_port), charset='utf8mb4')
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 788, in _request_authentication
    if int(self.server_version.split('.', 1)[0]) >= 5:
ValueError: invalid literal for int() with base 10: 'Inception2'

ERROR:default:Traceback (most recent call last):
  File "/opt/dba/archery_1.5.3/common/check.py", line 29, in inception
    conn = pymysql.connect(host=inception_host, port=int(inception_port), charset='utf8mb4')
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py", line 788, in _request_authentication
    if int(self.server_version.split('.', 1)[0]) >= 5:
ValueError: invalid literal for int() with base 10: 'Inception2'
```

### 版本信息
应用版本/分支：手工部署 1.5.3

**Comment by think-coding** [comment]
同一个机器下，连接同一个inception。
runserver 启动的1.3.8可以连接，startup.sh 启动的 报错：
ValueError: invalid literal for int() with base 10: 'Inception2'

**Comment by LeoQuote** [comment]
建议使用推荐inception 重试 https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#inception_host

**Comment by think-coding** [comment]
是inception 啊，不是goinception

**Comment by hhyo** [comment]
看faq吧，这个报错信息网上也有很多

**Comment by think-coding** [comment]
faq里没有，网上我看了，类型转换异常，但是我输入的是数字，还是报错。

**Comment by think-coding** [comment]
修改如下代码后，成功连接：
vim /opt/dba/archery_1.5.3/venv4archery150/lib/python3.6/site-packages/pymysql/connections.py
将 786行
```
def _request_authentication(self):
    # https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
    if int(self.server_version.split('.', 1)[0]) >= 5:
        self.client_flag |= CLIENT.MULTI_RESULTS
```
修改为
```
def _request_authentication(self):
    # https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
    if self.server_version.split('.', 1)[0] == 'Inception2':
        self.client_flag |= CLIENT.MULTI_RESULTS
    elif int(self.server_version.split('.', 1)[0]) >= 5:
        self.client_flag |= CLIENT.MULTI_RESULTS
```

**Comment by think-coding** [comment]
已更新wiki FAQ
