### ISSUE TITLE
[ 问题咨询 ] 回滚sql报错

### ISSUE THREAD

**Issue by Marco1221** [hhyo/Archery#182]
### 问题描述
sql上线选择备份，
流程正常结束后查看该工单，
点击最底下的 ”查看回滚SQL“报错
----
connect() argument 2 must be str, not None
----

archery 日志如下

`[2019-05-09 15:35:14,174][MainThread:139964621322048][task_id:default][views.py:128][ERROR]- Traceback (most recent call last):
  File "/opt/archery/sql/views.py", line 126, in rollback
    list_backup_sql = query_engine.get_rollback()
  File "/opt/archery/sql/engines/mysql.py", line 279, in get_rollback
    return inception_engine.get_rollback_list(self.workflow.id)
  File "/opt/archery/sql/engines/inception.py", line 82, in get_rollback_list
    conn = self.get_backup_connection()
  File "/opt/archery/sql/engines/inception.py", line 33, in get_backup_connection
    charset='utf8')
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 2 must be str, not None

ERROR:default:Traceback (most recent call last):
  File "/opt/archery/sql/views.py", line 126, in rollback
    list_backup_sql = query_engine.get_rollback()
  File "/opt/archery/sql/engines/mysql.py", line 279, in get_rollback
    return inception_engine.get_rollback_list(self.workflow.id)
  File "/opt/archery/sql/engines/inception.py", line 82, in get_rollback_list
    conn = self.get_backup_connection()
  File "/opt/archery/sql/engines/inception.py", line 33, in get_backup_connection
    charset='utf8')
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 2 must be str, not None
`

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by yzypals** [comment]
系统管理-配置项管理-系统设置-inception 备份库信息没填写

**Comment by Marco1221** [comment]
我设置了，
10.136.0.128 为 docker 宿主机IP地址

0.0.0.0:6669->6669/tcp              inception

`INCEPTION_HOST
10.136.0.128
INCEPTION_PORT
6669
REMOTE_BACKUP_HOST
10.136.0.128
REMOTE_BACKUP_PORT
6669
REMOTE_BACKUP_USER

REMOTE_BACKUP_PASSWORD`

请问这样设置对么？

**Comment by Marco1221** [comment]
> 系统管理-配置项管理-系统设置-inception 备份库信息没填写

我设置了，
10.136.0.128 为 docker 宿主机IP地址

0.0.0.0:6669->6669/tcp inception

`INCEPTION_HOST
10.136.0.128
INCEPTION_PORT
6669
REMOTE_BACKUP_HOST
10.136.0.128
REMOTE_BACKUP_PORT
6669
REMOTE_BACKUP_USER

REMOTE_BACKUP_PASSWORD`

请问这样设置对么？

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#inception%E9%85%8D%E7%BD%AE 请参考文档正确配置inception

**Comment by hhyo** [comment]
同上看文档即可，对照文档这个配置明显错了

> > 系统管理-配置项管理-系统设置-inception 备份库信息没填写
> 
> 我设置了，
> 10.136.0.128 为 docker 宿主机IP地址
> 
> 0.0.0.0:6669->6669/tcp inception
> 
> `INCEPTION_HOST
> 10.136.0.128
> INCEPTION_PORT
> 6669
> REMOTE_BACKUP_HOST
> 10.136.0.128
> REMOTE_BACKUP_PORT
> 6669
> REMOTE_BACKUP_USER
> 
> REMOTE_BACKUP_PASSWORD`
> 
> 请问这样设置对么？
