### ISSUE TITLE
mongo工单执行错误

### ISSUE THREAD

**Issue by zhouyi-up** [hhyo/Archery#1918]
### 重现步骤

1.填写工单SQL
db.test.insertMany([{ test1:1 }]);
2.中间所有人审核
3.点击立即执行

### 预期外的结果

报错
local variable 'msg' referenced before assignment : Traceback (most recent call last):
File "/opt/venv4archery/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/opt/archery/sql/utils/execute_sql.py", line 44, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/opt/archery/sql/engines/mongo.py", line 404, in execute_workflow
return self.execute(
File "/opt/archery/sql/engines/mongo.py", line 410, in execute
self.get_master()
File "/opt/archery/sql/engines/mongo.py", line 368, in get_master
master = self.exec_cmd(sql)
File "/opt/archery/sql/engines/mongo.py", line 362, in exec_cmd
return msg
UnboundLocalError: local variable 'msg' referenced before assignment
![image](https://user-images.githubusercontent.com/28778415/195792372-7a9e6ab7-7986-4ffa-9f9c-b4c62c1fc977.png)

### 版本

1.9.0

### 部署方式

Docker

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/813a16e37fa0ad63eaa3de80ceed11522d41e6a7/sql/engines/mongo.py#L282

确认下这几个信息是否有配置

**Comment by hhyo** [comment]
#1893
