### ISSUE TITLE
oracle建表报Json decode failed.执行结果Json解析失败, 请联系管理员

### ISSUE THREAD

**Issue by SoHuDrgon** [hhyo/Archery#2031]
### 重现步骤

1.建表语句提交
CREATE TABLE 
    MER_CARD_RECORD 
    ( 
        TRANS_SERIAL_NUMBER VARCHAR2(70) NOT NULL, 
        MER_ID              VARCHAR2(32) NOT NULL, 
        CREATE_TIME         VARCHAR2(32), 
        PRIMARY KEY (TRANS_SERIAL_NUMBER) 
    );
2.审核报
Json decode failed.执行结果Json解析失败, 请联系管理员
日志报：
[2023-01-11 13:58:33,684][MainThread:139742192273216][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table MER_CARD_RECORD (TRANS_SERIAL_NUMBER INTEGER not null,
                                                          MER_ID VARCHAR2(32) not null,
                                                                              CREATE_TIME VARCHAR2(32),
                                                                                          primary key (TRANS_SERIAL_NUMBER))，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

3.SQL执行后
![截屏2023-01-11 下午2 06 11](https://user-images.githubusercontent.com/11847516/211730143-8fe271eb-3d4b-4a55-bf85-5244074f6293.png)
没有执行成功。库里没这个表。

### 预期外的结果

希望能执行成功

### 日志文本

```shell
[2023-01-11 13:58:33,684][MainThread:139742192273216][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table MER_CARD_RECORD (TRANS_SERIAL_NUMBER INTEGER not null,
                                                          MER_ID VARCHAR2(32) not null,
                                                                              CREATE_TIME VARCHAR2(32),
                                                                                          primary key (TRANS_SERIAL_NUMBER))，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### 版本

1.9.1

### 部署方式

Docker

**Comment by bwcxyk** [comment]
同样的问题

**Comment by hhyo** [comment]
#2132

**Comment by bwcxyk** [comment]
> #2132

修改之后执行建表语句仍然获取不到受影响行数

**Comment by eckezhang** [comment]
修改之后执行建表语句仍然获取不到受影响行数

**Comment by tonyhu214** [comment]
#2262
