### ISSUE TITLE
[ 问题咨询 ] SQL查询按钮没反应，一分钟后返回错误

### ISSUE THREAD

**Issue by eason0420** [hhyo/Archery#211]
### 问题描述
使用管理员账号登录后使用查询功能
表结构可以查看，但是执行计划 和SQL查询按钮，没反应，一分钟后返回错误
【
Error
--
查询时间超过 60 秒，已被主动终止，请优化语句或者联系管理员。
】

日志如下：
[2019-05-17 13:35:30,344][MainThread:140320735205184][task_id:django-q][tasks.py:60][INFO]- Enqueued 14
[2019-05-17 13:35:30,345][MainThread:140320735205184][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('beer-one-lactose-carolina', '58a217fe1f5d44a297a21a5b9042ba49')
[2019-05-17 13:36:43,780][MainThread:140320735205184][task_id:django-q][tasks.py:60][INFO]- Enqueued 15
[2019-05-17 13:36:43,780][MainThread:140320735205184][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('december-crazy-berlin-four', '6964a39e89554dbca25bad404d5b85df')

### 版本信息
 - 应用版本/分支：Release v1.5.3  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
看你的日志有推送的日志但是没有消费的日志, 可能是qcluter 没起来, 请用

```
docker-compose -f docker-compose.yml exec archery sh
```
进入容器终端
然后使用 

```
source /opt/venv4archery/bin/activate
python3 manage.py qmonitor
```
查看qcluster状态

**Comment by eason0420** [comment]
```
(venv4archery) [root@3feb2b49a2b8 archery]# python3 manage.py qmonitor
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/opt/venv4archery/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/management/commands/qmonitor.py", line 4, in <module>
    from django_q.monitor import monitor
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/monitor.py", line 4, in <module>
    from blessed import Terminal
  File "/opt/venv4archery/lib/python3.6/site-packages/blessed/__init__.py", line 10, in <module>
    from blessed.terminal import Terminal
  File "/opt/venv4archery/lib/python3.6/site-packages/blessed/terminal.py", line 8, in <module>
    import curses
  File "/usr/local/python3/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by LeoQuote** [comment]
目前没有特别好的方案, 从这个现象来看应该是qcluster 没起来, 我建议你重启一下服务
```
docker-compose -f docker-compose.yml down && docker-compose -f docker-compose.yml up
```

**Comment by LeoQuote** [comment]
@hhyo 上面那个qmonitor报错是因为python编译的时候没有 cursor 的header文件, 可以在 Dockerfile 里加一下安装一下
```
yum install ncurses-devel
```

**Comment by hhyo** [comment]
可以升级1.6.0
