### ISSUE TITLE
[ bug ] mysql 查询报 2019, "Can't initialize character set utf8mb4 

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#214]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

查询报 ``Can't initialize character set utf8mb4`` , 我将mysql.py中的charset改为了utf8后解决, 详细错误日志见下方

### 重现步骤
在查询页面依次选择实例, 数据库, 表 

### 期待结果和实际结果
期待结果：
返回表结构
实际结果:
前端报错 `` 2019, "Can't initialize character set utf8mb4 ``

后端日志:

```
[2019-05-17 17:54:15,126][MainThread:140095841003264][task_id:default][mysql.py:104][ERROR]- MySQL语句执行报错，语句：show databases，错误信息Traceback (most recent call last):
  File "/home/work/archery/sql/engines/mysql.py", line 91, in query
    conn = self.get_connection(db_name=db_name)
  File "/home/work/archery/sql/engines/mysql.py", line 28, in get_connection
    charset='utf8mb4')
  File "/home/work/venvs/archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/home/work/venvs/archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 235, in __init__
    self.set_character_set(charset)
  File "/home/work/venvs/archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 358, in set_character_set
    super(Connection, self).set_character_set(charset)
_mysql_exceptions.OperationalError: (2019, "Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)")
```
### 版本信息
应用版本/分支：

master

部署方式：手工部署

**Comment by hhyo** [comment]
mysql 是什么版本啊，真不行可以使用 `'init_command':'set names utf8mb4;'`来初始化

**Comment by LeoQuote** [comment]
我比较怀疑是我这边服务器是utf8 的, 造成这个问题, 是不是charset真的要写到实例表里, 来解决字符编码的问题?

**Comment by LeoQuote** [comment]
@hhyo 经查是本地mysql 客户端和devel包版本过低导致的.
mysql 客户端是 5.1 , 服务端是 5.7

解决方案如下:

1. 升级mysql 客户端和 devel包到5.7 
2. pip 卸载mysqlclient 和 pymysql 包
```
pip uninstall mysqlclient pymysql
```
3. 重新安装 ``pip install -r requirements.txt``
4. 重启archery 和qcluster
