### ISSUE TITLE
[ 问题咨询 ]sqlserver是否支持SQL上线提交功能?

### ISSUE THREAD

**Issue by MisKatherine** [hhyo/Archery#227]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
1.针对redis，redis主从和cluster的操作一样吗？比如删除匹配的key*，cluster是每个主节点都操作一遍删除，SQL审核平台也是要每个主节点都删除吗？（现有cluster没有域名，连接信息也是指定IP）
2.sqlserver是否支持SQL上线提交功能？
### 版本信息
 - 应用版本/分支：v1.6.0
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
针对 mssql 的上线功能在 https://github.com/hhyo/Archery/pull/212 这个pr中已经实现, 但由于备份机制有不同, 尚未merge, 还在思考有没有更好的方案

mssql 采用的备份方法是在用户填写上线单时, 选择需要备份的表, 然后在操作前做整表备份.

如果有兴趣可以拉取对应分支, 自己部署尝试

**Comment by MisKatherine** [comment]
在SQL审核平台提交SQLserver操作，报错信息如下。
![image](https://user-images.githubusercontent.com/50308927/58458979-fc37cb00-815c-11e9-929f-985ac399ad77.png)
```
[2019-05-28 12:02:31,817][MainThread:140264516069184][task_id:django-q][cluster.py:333][INFO]- Processed [edward-butter-delaware-four]
[2019-05-28 12:02:34,114][MainThread:140264516069184][task_id:django-q][cluster.py:305][DEBUG]- queueing from django_q:archery:q
[2019-05-28 12:02:34,114][MainThread:140264516069184][task_id:django-q][cluster.py:356][INFO]- Process-1:1 processing [december-kentucky-alanine-river]
[2019-05-28 12:02:34,131][MainThread:140264516069184][task_id:django-q][signals.py:26][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [december-kentucky-alanine-river] because 'dict' object has no attribute '__dict__'
[2019-05-28 12:02:34,132][MainThread:140264516069184][task_id:django-q][cluster.py:336][ERROR]- Failed [december-kentucky-alanine-river] - 'MssqlEngine' object has no attribute 'execute_workflow' : Traceback (most recent call last):
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/dba/Archery/sql/utils/execute_sql.py", line 27, in execute
    return execute_engine.execute_workflow(workflow=workflow_detail)
AttributeError: 'MssqlEngine' object has no attribute 'execute_workflow'

```

**Comment by LeoQuote** [comment]
你对我的说法有些误解, 这个pr尚未merge , 请单独拉取对应的分支进行操作.

**Comment by LeoQuote** [comment]
mssql 执行已合并到master , 可以手动部署master 分支进行尝试.
