### ISSUE TITLE
[ 问题咨询 ] django.core.exceptions.PermissionDenied

### ISSUE THREAD

**Issue by wl-sre** [hhyo/Archery#241]
### 问题描述
我安装好了之后，用LDAP用户去登录，始终是报下面的一个错误,尝试重新导入数据好几次，问题依然存在，感觉是初始化的时候，有一些默认权限组没有导入数据导致的，使得普通LDAP用户登录后，没有默认权限，进而报下面的错误。希望看到后，帮忙定位下，谢谢您的及时回复！
```
b'SELECT `django_content_type`.`app_label`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `auth_group_permissions` ON (`auth_permission`.`id` = `auth_group_permissions`.`permission_id`) INNER JOIN `auth_group` ON (`auth_group_permissions`.`group_id` = `auth_group`.`id`) INNER JOIN `sql_users_groups` ON (`auth_group`.`id` = `sql_users_groups`.`group_id`) INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `sql_users_groups`.`users_id` = 2'
[2019-05-31 10:27:05,872][Thread-25:140152328414976][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/data/apps/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/apps/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/data/apps/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

### 版本信息
 - 应用版本/分支：Release Archery-1.6.0 
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
感谢你的反馈，请问你有没有根据文档创建一个默认权限组，并且在系统设置内进行关联呢？

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/wiki#%E6%B7%BB%E5%8A%A0%E6%9D%83%E9%99%90%E7%BB%84

**Comment by wl-sre** [comment]
谢谢您的及时回复，请问这个权限组在哪里可以明确指定是默认的权限组呢，还是说，只能是LDAP的用户登录后，人工进行手动操作 LDAP用户----关联---权限组 呢？
谢谢

**Comment by LeoQuote** [comment]
在左边菜单里的系统管理-配置项管理中有默认权限组的配置，只要在django后台建立一个组，然后将组名字填入这里，之后的新用户就都会自动关联，不需要人工干预。

**Comment by wl-sre** [comment]
谢谢，已经可以正常运行了。谢谢！
