### ISSUE TITLE
会话管理：报错

### ISSUE THREAD

**Issue by eqieyiran** [hhyo/Archery#255]
### 问题描述
点击会话管理，选择阿里云RDS的MySQL数据库提示报错，自建的数据库是正常的。数据库的权限方面设置都是一样的。请问怎么修复。

报错信息：
数据加载失败！请检查接口返回信息和错误日志！
![image](https://user-images.githubusercontent.com/30651724/59003642-67625b00-8849-11e9-94d3-959073292d28.png)
错误日志：（docker logs archery -f --tail=50）
[2019-06-06 10:52:50,769][MainThread:140591380117312][task_id:django.request][exception.py:118][ERROR]- Internal Server Error: /db_diagnostic/process/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/db_diagnostic.py", line 29, in process
    result = aliyun_process_status(request)
  File "/opt/archery/sql/aliyun_rds.py", line 102, in process_status
    {"Language": "zh", "Command": command_type})
  File "/opt/archery/common/utils/aliyun_sdk.py", line 87, in RequestServiceOfCloudDBA
    result = self.request_api(request, values)
  File "/opt/archery/common/utils/aliyun_sdk.py", line 35, in request_api
    result = self.clt.do_action_with_exception(request)
AttributeError: 'Aliyun' object has no attribute 'clt'

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
rds请按照文档配置ak信息
