### ISSUE TITLE
[ bug ]用户申请表级别权限不能正常查询，仍提示无查询权限；django 后台筛选用户报 500 错误

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#259]
### 重现步骤
用户申请表级别权限不能正常查询，仍提示无查询权限。

日志中报错：tb_list 和 table_list 不匹配。

### 期待结果和实际结果
期待结果：
用户可以正常查询，后台筛选用户功能正常

实际结果:
用户有权限不能查询，后台筛选用户报 500 错误
### 截图
![image](https://user-images.githubusercontent.com/35367394/59169857-97be3800-8b6e-11e9-97cd-5d9f986eb040.png)

### 错误日志
/downloads/log/archery.log
```
[2019-06-10 10:46:05,679][MainThread:139641528469312][task_id:django.request][exception.py:118][ERROR]- Internal Server Error: /admin/sql/queryprivilegesapply/
Traceback (most recent call last):
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/options.py", line 575, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1592, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/options.py", line 706, in get_changelist_instance
    self,
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 76, in __init__
    self.queryset = self.get_queryset(request)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 356, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/contrib/admin/options.py", line 958, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/query.py", line 839, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/query.py", line 857, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1271, in _add_q
    current_negated, allow_joins, split_subq)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1153, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1015, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/opt/dba/Archery/venv4archery160/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1379, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'tb_list' into field. Choices are: apply_id, audit_auth_groups, create_time, db_list, group_id, group_name, instance, instance_id, limit_num, priv_type, status, sys_time, table_list, title, user_display, user_name, valid_date
```
-->
### 版本信息
应用版本/分支：

部署方式：手工部署 v1.6.1

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/sql/models.py model层的字段名为table_name 

可以改model层解决

**Comment by LeoQuote** [comment]
等等后续把这块的单元测试加上
