### ISSUE TITLE
[ bug ] 添加了sql上线执行时间选择后，查看历史工单会报错？

### ISSUE THREAD

**Issue by AceAttorney** [hhyo/Archery#280]
### 重现步骤
sql审核-->sql上线 点击工单名称查看详情后报错。

添加了sql上线执行时间选择后，查看历史工单会报错？

### 期待结果和实际结果
期待结果：

实际结果:

### 截图

![image](https://user-images.githubusercontent.com/13723456/59664382-8a92f000-91e3-11e9-90a6-6a9aa9078809.png)

### 错误日志
```
[2019-06-18 15:54:49,257][MainThread:140016683247424][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'sql_workflow.run_date_start' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Archery/Archery/sql/views.py", line 78, in detail
    workflow_detail = get_object_or_404(SqlWorkflow, pk=workflow_id)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/shortcuts.py", line 87, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/models/query.py", line 1182, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/root/anaconda3/envs/archery/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'sql_workflow.run_date_start' in 'field list'")

```

### 版本信息
应用版本/分支：
1.6.3

部署方式：Docker、手工部署
手工部署

**Comment by hhyo** [comment]
升级1.6.2的脚本执行了没
https://github.com/hhyo/Archery/blob/master/src/init_sql/v1.6.1_v1.6.2.sql#L41

**Comment by AceAttorney** [comment]
前两天升级执行了一次 发现现在又加了几行。。。

**Comment by hhyo** [comment]
一般不要用master分支，只有release版本才是稳定版

**Comment by yzypals** [comment]
r使用请用release 开发可以用master ~！~
