### ISSUE TITLE
GoInception检测语句报错

### ISSUE THREAD

**Issue by ferriswang** [hhyo/Archery#2886]
### 重现步骤

在SQL上线模块，无论提交什么sql，即使是select * from tb1;都会报如下错误：
{"errors":"GoInception检测语句报错，错误信息：\n(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'inception_magic_start;\\n                            inception set session ghost_a' at line 2\")"}

### 预期外的结果

![1](https://github.com/user-attachments/assets/66119c23-bc88-4833-8102-2c10b3e01dbf)
![2](https://github.com/user-attachments/assets/1f62f173-64bc-4191-a22b-7eb6f7fac819)

### 版本

1.11.3

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

Mysql:8.0
Browsers: Chrome
goInception: latest
Docker version 26.1.2
Docker Compose version v2.20.2

**Comment by zmix999** [comment]
SQL上线模块不支持SELECT语句

**Comment by RonadoLong** [comment]
同样的问题，请问解决了吗

**Comment by goodluck-yan** [comment]
我也遇到了这个问题，有解决方案吗

![Image](https://github.com/user-attachments/assets/fba15338-7c55-4e9f-b2a1-07e729996dc4)

**Comment by cooker** [comment]
![Image](https://github.com/user-attachments/assets/8edb96e9-5a22-475d-9d1c-e8086fe54f11) 遇到过吗？？？

![Image](https://github.com/user-attachments/assets/f0fc1135-8887-426c-a404-e691b9f934f9)

**Comment by lhsaq2009** [comment]
<img width="1378" height="647" alt="Image" src="https://github.com/user-attachments/assets/d5c1f731-092c-4aae-afa3-d13c9273ff9e" />

© Archery (v1.12.0)

**Comment by lhsaq2009** [comment]
```
[2025-07-29 23:53:48,423][MainThread:139991684368192][task_id:default][goinception.py:174][WARNING]- goInception语句执行报错，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/goinception.py", line 163, in query
    effect_row = cursor.execute(sql)
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'inception_magic_start;\n                            \n                            ' at line 2")

2025-07-29 23:53:48,423 - default - WARNING - goInception语句执行报错，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/goinception.py", line 163, in query
    effect_row = cursor.execute(sql)
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.11/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'inception_magic_start;\n                            \n                            ' at line 2")

2025-07-29 23:53:48,459 - django.request - WARNING - Bad Request: /api/v1/workflow/sqlcheck/
```

**Comment by lhsaq2009** [comment]
```
delete from up_360_cdt_qc_t1 where ID = '309E2DD8-1B42-9E12-3F43-9A5587154FE4' LIMIT 1;


{"errors":"GoInception检测语句报错，错误信息：\n(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'inception_magic_start;\\n                            \\n                            ' at line 2\")"}
```
