### ISSUE TITLE
[ bug ]慢查询统计 导出功能提示报错

### ISSUE THREAD

**Issue by eqieyiran** [hhyo/Archery#312]
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
 慢查询统计页面进行选择对应实例后有显示慢查明细，点击导出功能提示报错

### 期待结果和实际结果
期待结果：
导出有效的数据到csv文件
实际结果:
生成csv文件，当时里面只有标题没数据
### 截图

![image](https://user-images.githubusercontent.com/30651724/60721212-c528b680-9f5f-11e9-906e-259f35ceae8b.png)

 
### 错误日志
[2019-07-05 20:00:07,488][MainThread:140664305846080][task_id:django.request][exception.py:118][ERROR]- Internal Server Error: /slowquery/review/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 40, in slowquery_review
    limit = int(request.POST.get('limit'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2019-07-05 20:00:34,897][MainThread:140664305846080][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 109, in slowquery_review_history
    limit = int(request.POST.get('limit'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
ERROR:default:Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 109, in slowquery_review_history
    limit = int(request.POST.get('limit'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2019-07-05 20:00:34,898][MainThread:140664305846080][task_id:django.request][exception.py:118][ERROR]- Internal Server Error: /slowquery/review_history/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 109, in slowquery_review_history
    limit = int(request.POST.get('limit'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

 
### 版本信息
应用版本/分支：
部署方式：Docker

**Comment by hhyo** [comment]
感谢反馈

不支持导出，可以自己到库里面去查，后面这块会隐藏掉

**Comment by eqieyiran** [comment]
是哦，从数据库mysql_slow_query_review查更快
