### ISSUE TITLE
[ 问题咨询 ]提交DDL审核时提示Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#319]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：Docker

在进行DDL操作SQL检测时报错，错误日志

[2019-07-10 15:54:48,347][MainThread:140654219380544][task_id:default][mysql.py:170][DEBUG]- Inception检测语句报错：错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 168, in execute_check
    inc_check_result = inception_engine.execute_check(instance=self.instance, db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/goinception.py", line 38, in execute_check
    inception_result = self.query(sql=inception_sql)
  File "/opt/archery/sql/engines/goinception.py", line 86, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 25, in get_connection
    self.conn = MySQLdb.connect(host=go_inception_host, port=go_inception_port, charset='utf8mb4')
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 250, in __init__
    self.autocommit(autocommit)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 256, in autocommit
    _mysql.connection.autocommit(self, on)
_mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

DEBUG:default:Inception检测语句报错：错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 168, in execute_check
    inc_check_result = inception_engine.execute_check(instance=self.instance, db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/goinception.py", line 38, in execute_check
    inception_result = self.query(sql=inception_sql)
  File "/opt/archery/sql/engines/goinception.py", line 86, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 25, in get_connection
    self.conn = MySQLdb.connect(host=go_inception_host, port=go_inception_port, charset='utf8mb4')
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 250, in __init__
    self.autocommit(autocommit)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 256, in autocommit
    _mysql.connection.autocommit(self, on)
_mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

**Comment by hhyo** [comment]
![image](https://user-images.githubusercontent.com/8842982/60951692-40a5b180-a32c-11e9-9cb7-d10f3d8fa832.png)

**Comment by a5546868001** [comment]
docker部署的 需要把之前的goinception容器删掉么

**Comment by hhyo** [comment]
goinception地址：https://hub.docker.com/r/hanchuanchuan/goinception/tags
- 调整yaml文件，增加版本信息，例如要更新为v1.0-rc4 
```
image: hanchuanchuan/goinception:v1.0-rc4 
```
- 重新执行
```
docker-compose -f docker-compose.yml up -d
```

**Comment by a5546868001** [comment]
收到，已解决，感谢大佬支持
