### ISSUE TITLE
[ 问题咨询 ]阿里云RDS查看慢日志报错

### ISSUE THREAD

**Issue by sum86** [hhyo/Archery#376]
### 问题描述
点击慢日志统计及明细，弹框提示：数据加载失败！请检查接口返回信息和错误日志！
日志报错如下：
[2019-08-09 18:18:58,378][MainThread:140613478385472][task_id:django.request][exception.py:118][ERROR]- Internal Server Error: /slowquery/review_history/
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/slowlog.py", line 107, in slowquery_review_history
    result = aliyun_rds_slowquery_review_history(request)
  File "/opt/archery/sql/aliyun_rds.py", line 74, in slowquery_review_history
    slowsql = Aliyun().DescribeSlowLogRecords(instance_info.rds_dbinstanceid, start_time, end_time, **values)
  File "/opt/archery/common/utils/aliyun_sdk.py", line 71, in DescribeSlowLogRecords
    result = self.request_api(request, values)
  File "/opt/archery/common/utils/aliyun_sdk.py", line 35, in request_api
    result = self.clt.do_action_with_exception(request)
AttributeError: 'Aliyun' object has no attribute 'clt'

### 版本信息
 - 应用版本/分支：Release v1.6.6
 - 部署方式：Docker部署
 - 操作系统：centos7.6

**Comment by hhyo** [comment]
实例关联了阿里云RDS，但是没有配置AK信息或者AK配置不正确

**Comment by sum86** [comment]
谢谢，已解决，通过首页--->SQL--->SQL管理--->阿里云认证信息添加 AK解决此问题，希望后期增加一些提示。
