### ISSUE TITLE
[ bug ] pg一键查询报错 

### ISSUE THREAD

**Issue by yzypals** [hhyo/Archery#380]
### 错误日志
前端界面提示 relation "mem_person" does not exist LINE 1: select * from mem_person; ^
服务器日志
```
[13/Aug/2019 14:18:19] "GET /query/querylog/?star=&query_log_id=&limit=14&offset=0&search=&_=1565676411807 HTTP/1.1" 200 1087
[13/Aug/2019 14:18:23] "POST /instance/instance_resource/ HTTP/1.1" 200 59
[2019-08-13 14:18:25,389][Thread-100:139958097188608][task_id:default][pgsql.py:160][ERROR]- PgSQL命令执行报错，语句：select * from mem_person;， 错误信息：Traceback (most recent call last):
  File "/home/yingzy/Desktop/djangodev/Archery/sql/engines/pgsql.py", line 148, in _query
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "mem_person" does not exist
LINE 1: select * from mem_person;
                      ^


ERROR:default:PgSQL命令执行报错，语句：select * from mem_person;， 错误信息：Traceback (most recent call last):
  File "/home/yingzy/Desktop/djangodev/Archery/sql/engines/pgsql.py", line 148, in _query
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "mem_person" does not exist
LINE 1: select * from mem_person;
                      ^


[13/Aug/2019 14:18:25] "POST /query/ HTTP/1.1" 200 136
[13/Aug/2019 14:18:25] "POST /instance/instance_resource/ HTTP/1.1" 200 125

```
### 版本信息
应用版本/分支：
master最新版 1.6.7
部署方式：Docker、手工部署
手工部署

**Comment by yzypals** [comment]
这里应该是 pg 有 实例  模式 比其他多一层 ，  一键查询的时候 没有吧模式带进去

**Comment by Liuzhj** [comment]
@yzypals @hhyo 

这个问题我也有遇到过。但我认为不是BUG，属于功能优化。

模式是支持选择的。在写SQL查询时，PG的表名需要加上双引号，而且大小写不能错。这样就不会出问题了。

**Comment by hhyo** [comment]
挂着也没用，关闭
