### ISSUE TITLE
[ bug ] 查询行数限制功能导致无法正常查询sql

### ISSUE THREAD

**Issue by yzypals** [hhyo/Archery#381]
### 重现步骤
有点复杂的语句 就会导致无法正常查询
下面这个是个例子
select s.*
from asp_common.base_contacts_sale s 
where s.org_id = '100000000' 
and s.sales_Id is null or s.PERSON_ID is null
这种sql 不能简单的在后面跟上WHERE ROWNUM <= 100
实际结果:
不能正常查询sql
### 错误日志
[13/Aug/2019 15:13:05] "POST /query/ HTTP/1.1" 200 77
[2019-08-13 15:14:23,268][Thread-59:139881859405568][task_id:default][oracle.py:184][ERROR]- Oracle 语句执行报错，语句：select s.*
from asp_common.base_contacts_sale s 
where s.org_id = '100000000' 
and s.sales_Id is null or s.PERSON_ID is null WHERE ROWNUM <= 100，错误信息Traceback (most recent call last):
  File "/home/yingzy/Desktop/djangodev/Archery/sql/engines/oracle.py", line 168, in query
    cursor.execute(sql)
cx_Oracle.DatabaseError: ORA-00933: SQL command not properly ended

ERROR:default:Oracle 语句执行报错，语句：select s.*
from asp_common.base_contacts_sale s 
where s.org_id = '100000000' 
and s.sales_Id is null or s.PERSON_ID is null WHERE ROWNUM <= 100，错误信息Traceback (most recent call last):
  File "/home/yingzy/Desktop/djangodev/Archery/sql/engines/oracle.py", line 168, in query
    cursor.execute(sql)
cx_Oracle.DatabaseError: ORA-00933: SQL command not properly ended

[13/Aug/2019 15:14:23] "POST /query/ HTTP/1.1" 200 77
### 版本信息
应用版本/分支：
master
部署方式：Docker、手工部署
手工部署

**Comment by yzypals** [comment]
这个bug 应该一直都存在的 ，  以前我都是把 查询行数限制功能的代码直接干掉的 。

**Comment by yzypals** [comment]
上面这个报错 先解决了  是where 没找到导致的，  至于负责语句加限制位置不正常的 后期修改。

**Comment by yzypals** [comment]
#384

**Comment by hhyo** [comment]
问题已修复
