### ISSUE TITLE
[ bug ]实例是sharding-proxy 时，数据字典功能不正常

### ISSUE THREAD

**Issue by WatchLucky** [hhyo/Archery#391]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1. docker 启动archer 
2. 添加实例 ： 添加sharding-proxy 实例
3. 实例管理--> 数据字典 --> 选择sharding-proxy 实例

### 期待结果和实际结果
期待结果：能够 查看对应数据库列表

实际结果:
弹出提示框 : 'str' object has no attribute 'decode'
### 错误日志
docker logs  77eb4c7cd621

ERROR:default:MySQL语句执行报错，语句：show databases，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 105, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 413, in _query
    self._post_get_result()
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 417, in _post_get_result
    self._rows = self._fetch_row(0)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 385, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 232, in string_decoder
    return s.decode(db.encoding)
AttributeError: 'str' object has no attribute 'decode'

### 版本信息
应用版本/分支：1.6.5

部署方式：Docker

**Comment by WatchLucky** [comment]
升级  mysqlclient 包至1.4.4  已经解决

**Comment by Bpazy** [comment]
此 issue 是否有更深入的调查结论？:)
