### ISSUE TITLE
[ bug ]长时间sql查询2013, 'Lost connection to MySQL server during query'

### ISSUE THREAD

**Issue by jamene** [hhyo/Archery#403]
在使用sql查询返回比较大和查询时间比较长的sql语句时会报下面这个错，
但是在navicate客户端使用相同的sql语句并没有相同报错
(2013, 'Lost connection to MySQL server during query')

### 期待结果和实际结果
期待结果：返回正确查询结果
实际结果: 报上述错误

### 错误日志

[2019-08-27 13:14:19,341][MainThread:140308315400000][task_id:default][mysql.py:118][ERROR]- MySQL语句执行报错，语句：select
错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 107, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

ERROR:default:MySQL语句执行报错，语句：select
  profitamount limit 100;，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 107, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

[2019-08-27 13:14:19,346][MainThread:140308315400000][task_id:default][tasks.py:31][DEBUG]- 删除task：query-1566882795.6197033
DEBUG:default:删除task：query-1566882795.6197033

### 版本信息
应用版本/分支：v1.6.6

部署方式：Docker部署

**Comment by hhyo** [comment]
参考：https://github.com/hhyo/archery/wiki/配置项说明#max_execution_time

**Comment by jamene** [comment]
非常感谢:）
