### ISSUE TITLE
[ 问题咨询 ]采取docker部署，Problem with dial: dial tcp: lookup mysql on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#432]
### 问题描述
采取docker部署，数据库使用已有的mysql 实例（5.7.20-log）。
删除了docker-compose.yml文件内的services mysql:，修改了archery/settings.py，
并授予了数据库用户all privileges权限，并验证可以从mysql 命令行成功登录数据库实例。
然后：
docker-compose -f docker-compose.yml up -d
docker logs archery -f --tail=50  发现一直报错：
![image](https://user-images.githubusercontent.com/54062997/64415028-115eb700-d0c7-11e9-96ca-9770923f3ab0.png)
然后执行“表结构初始化”步骤的 python3 manage.py makemigrations sql  报错：
(venv4archery) [root@0c6809f95e5f archery]# python3 manage.py makemigrations sql  
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 27, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 1200, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 1272, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 894, in check
    errors = super().check(**kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 206, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 303, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/validation.py", line 21, in check_field
    field_type = field.db_type(self.connection)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 648, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 133, in data_types
    if self.features.supports_microsecond_precision:
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 65, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 349, in mysql_version
    match = server_version_re.match(self.mysql_server_info)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 343, in mysql_server_info
    with self.temporary_connection() as cursor:
  File "/usr/local/python3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 576, in temporary_connection
    cursor = self.cursor()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")

### 版本信息
 - 应用版本/分支：Release v1.7.0 
 - 部署方式：Docker

**Comment by hhyo** [comment]
连不上数据库，修改yaml文件中archery wait mysql的连接信息，更换成外部数据库地址

**Comment by yuandajn578** [comment]
@hhyo 
请问具体是docker-compose.yml中的配置项：
entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s /opt/archery/src/docker/startup.sh"
的“tcp://mysql:3306”吧？
另外，请问路径“/opt/archery/src/docker/startup.sh”是自动创建的吗？与下载的源码包所在路径无关吧？

**Comment by yuandajn578** [comment]
> 连不上数据库，修改yaml文件中archery wait mysql的连接信息，更换成外部数据库地址

@hhyo 
修改为外部mysql连接地址后，docker日志不再报错，但是执行python3 manage.py makemigrations sql 时，仍然报错：
![image](https://user-images.githubusercontent.com/54062997/64424079-ab7c2a80-d0da-11e9-83b5-01ee9108d1a5.png)
难道不能使用127.0.0.1？

**Comment by yuandajn578** [comment]
感谢大神的指点，已经解决外部数据库无法连接的问题了，系统可以访问了，多谢多谢！
最新的版本是1.6.7还是1.7.0呢？
![image](https://user-images.githubusercontent.com/54062997/64424721-622cda80-d0dc-11e9-8e52-3d45b1ce1063.png)

**Comment by yidazhi** [comment]
@yuandajn578 大佬，我也遇到了同样的问题，修改为外部连接后，还是报不能连接数据库，请问你是如何解决，还请指点一下，谢谢
