### ISSUE TITLE
[ 问题咨询 ]mysql添加实例测试报错

### ISSUE THREAD

**Issue by baijiu1** [hhyo/Archery#461]
### 问题描述
mysql添加实例后，测试连接报错

### 版本信息
 - 应用版本/分支：Release v1.6.7
 - 部署方式：手工部署

报错信息：
[2019-09-27 11:32:32,680][Thread-1899:140641648502528][task_id:default][mysql.py:124][WARNING]- MySQL语句执行报错，语句：show binary logs;，错误信息Traceback (most recent call last):
  File "/app/Archery-1.6.7/sql/engines/mysql.py", line 111, in query
    conn = self.get_connection(db_name=db_name)
  File "/app/Archery-1.6.7/sql/engines/mysql.py", line 28, in get_connection
    connect_timeout=10)
  File "/app/py36/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/app/py36/lib64/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxxx' (110)")

WARNING:default:MySQL语句执行报错，语句：show binary logs;，错误信息Traceback (most recent call last):
  File "/app/Archery-1.6.7/sql/engines/mysql.py", line 111, in query
    conn = self.get_connection(db_name=db_name)
  File "/app/Archery-1.6.7/sql/engines/mysql.py", line 28, in get_connection
    connect_timeout=10)
  File "/app/py36/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/app/py36/lib64/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxxx' (110)")

**Comment by hhyo** [comment]
检查实例配置

**Comment by baijiu1** [comment]
> 检查实例配置

和其他实例配置都是一样的，只有这个实例测试连接的时候报错。
![image](https://user-images.githubusercontent.com/21596224/65745150-61acc000-e12d-11e9-8bd3-945ed418ba80.png)

**Comment by hhyo** [comment]
```
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on '173.248.226.6' (110)")
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxxx' (110)")
```

**Comment by baijiu1** [comment]
> ```
> _mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxxx' (110)")
> _mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxxx' (110)")
> ```

两个IP是一样的我想隐藏一下，只改了一个。。

**Comment by hhyo** [comment]
没有别的可能，就是配置错误，或者实例本身就不存在，再仔细检查下吧
