### ISSUE TITLE
[ 问题咨询 ]根据升级文档在线升级V1.7.0到1.7.1后，redis拒绝连接

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#505]
### 问题描述
根据升级文档在线升级V1.7.0到1.7.1后，redis拒绝连接，后台具体报错如下：
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    result = middleware.process_request(request)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/middleware/cache.py", line 133, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/cache.py", line 360, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/opt/venv4archery/lib/python3.6/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/opt/venv4archery/lib/python3.6/site-packages/django_redis/client/default.py", line 203, in get
    value = client.get(key)
  File "/opt/venv4archery/lib/python3.6/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/opt/venv4archery/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv4archery/lib/python3.6/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
### 版本信息
 - 应用版本/分支：Release v1.7.1
 - 部署方式：Docker

**Comment by yuandajn578** [comment]
docker-compose.yml：
services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server  --requirepass 123456
    expose:
      - "6379"

settings.py ：
# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "123456"
        }
    },
    "dingding": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "123456"
        }
    }
}

**Comment by hhyo** [comment]
老问题，docker桥接网络，使用容器名作为host，不要用127

**Comment by yuandajn578** [comment]
大神果然威武！
我是用的官方的settings.py，忘记修改redis host为容器名了。
多谢了。
