### ISSUE TITLE
新增工单没有邮件提醒

### ISSUE THREAD

**Issue by sky1006** [hhyo/Archery#53]
新增工单没有邮件提醒，审核和执行结束正常提醒

**Comment by sky1006** [comment]
1.4.1

**Comment by hhyo** [comment]
请按约定格式模板提交issue

请先确认消息接接收人是否满足文档中的条件，同时请贴出日志信息，消息推送都会记录日志

https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E6%B6%88%E6%81%AF%E9%80%9A%E7%9F%A5

**Comment by sky1006** [comment]
资源组，权限组都没有问题，日志如下
[20/Feb/2019 09:43:32] "POST /simplecheck/ HTTP/1.1" 200 897
[2019-02-20 09:43:33,838][Thread-9:1711668][task_id:django-q][tasks.py:60][INFO]- Enqueued 1
INFO:django-q:Enqueued 1
[2019-02-20 09:43:33,839][Thread-9:1711668][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('kentucky-six-kilo-xray', 'a479822f54cb481f88a9c494c068d380')
DEBUG:django-q:Pushed ('kentucky-six-kilo-xray', 'a479822f54cb481f88a9c494c068d380')
[20/Feb/2019 09:43:33] "POST /autoreview/ HTTP/1.1" 302 0
[20/Feb/2019 09:43:34] "GET /detail/138/ HTTP/1.1" 200 39826

**Comment by LeoQuote** [comment]
从日志来看，发邮件的任务已经发过去了，但是似乎没有执行的日志，可能在后面？后面还有django-q 的日志吗？

**Comment by sky1006** [comment]
没有了

**Comment by sky1006** [comment]
审核通过日志，能发邮件
[20/Feb/2019 09:43:34] "GET /detail/138/ HTTP/1.1" 200 39826

[2019-02-20 10:07:00,937][Thread-11:1712440][task_id:django-q][tasks.py:60][INFO]- Enqueued 1
INFO:django-q:Enqueued 1
[2019-02-20 10:07:00,937][Thread-11:1712440][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('jersey-maryland-indigo-network', 'aac84b40e1f24cdaa61d8a553878cb12')
DEBUG:django-q:Pushed ('jersey-maryland-indigo-network', 'aac84b40e1f24cdaa61d8a553878cb12')
[20/Feb/2019 10:07:01] "POST /passed/ HTTP/1.1" 302 0
[20/Feb/2019 10:07:01] "GET /detail/138/ HTTP/1.1" 200 39911

**Comment by hhyo** [comment]
按照FAQ里面的说明来获取日志，主要是download里面的archery.log，gunicron的日志比较简单，看不到具体信息

**Comment by sky1006** [comment]
download里面日志信息差不多
notify(audit_info=audit_info,workflow_url=workflow_url,email_cc=kwargs.get('list_cc_addr', []),timeout=60)  这样可以直接发送，async_task就不行了，这种情况怎么调试

[2019-02-20 09:43:33,838][Thread-9:1711668][task_id:django-q][tasks.py:60][INFO]- Enqueued 1
[2019-02-20 09:43:33,839][Thread-9:1711668][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('kentucky-six-kilo-xray', 'a479822f54cb481f88a9c494c068d380')
[2019-02-20 10:07:00,937][Thread-11:1712440][task_id:django-q][tasks.py:60][INFO]- Enqueued 1
[2019-02-20 10:07:00,937][Thread-11:1712440][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('jersey-maryland-indigo-network', 'aac84b40e1f24cdaa61d8a553878cb12')

**Comment by LeoQuote** [comment]
可能是你的django-q 没启动、请问你是怎么启动的？docker？git clone 自己启动？

**Comment by LeoQuote** [comment]
下次请按模版提issue，启动方式和版本在模版里都要填写的。

**Comment by sky1006** [comment]
docker启动，审核和执行结束都能发邮件，说明django-q是启动的吧

**Comment by hhyo** [comment]
完整的启动日志应该是这样的：
```
[2019-02-20 22:03:39,928][MainThread:140489457207104][task_id:django-q][cluster.py:53][INFO]- Q Cluster-15 starting.
[2019-02-20 22:03:40,053][MainThread:140489457207104][task_id:django-q][cluster.py:348][INFO]- Process-1:1 ready for work at 27
[2019-02-20 22:03:40,067][MainThread:140489457207104][task_id:django-q][cluster.py:348][INFO]- Process-1:2 ready for work at 28
[2019-02-20 22:03:40,069][MainThread:140489457207104][task_id:django-q][cluster.py:348][INFO]- Process-1:4 ready for work at 30
[2019-02-20 22:03:40,084][MainThread:140489457207104][task_id:django-q][cluster.py:319][INFO]- Process-1:5 monitoring at 31
[2019-02-20 22:03:40,086][MainThread:140489457207104][task_id:django-q][cluster.py:284][INFO]- Process-1:6 pushing tasks at 32
[2019-02-20 22:03:40,075][MainThread:140489457207104][task_id:django-q][cluster.py:201][INFO]- Process-1 guarding cluster at 26
[2019-02-20 22:03:40,081][MainThread:140489457207104][task_id:django-q][cluster.py:348][INFO]- Process-1:3 ready for work at 29
[2019-02-20 22:03:40,103][MainThread:140489457207104][task_id:django-q][cluster.py:204][INFO]- Q Cluster-15 running.
[2019-02-20 22:04:10,627][MainThread:140078435297088][task_id:django-q][tasks.py:60][INFO]- Enqueued 1
[2019-02-20 22:04:10,627][MainThread:140078435297088][task_id:django-q][tasks.py:61][DEBUG]- Pushed ('angel-avocado-oscar-burger', '970b8f16896f4da49eb9f37c588c6ca4')
[2019-02-20 22:04:10,628][MainThread:140489457207104][task_id:django-q][cluster.py:305][DEBUG]- queueing from django_q:archery:q
[2019-02-20 22:04:10,629][MainThread:140489457207104][task_id:django-q][cluster.py:356][INFO]- Process-1:1 processing [angel-avocado-oscar-burger]
[2019-02-20 22:04:10,723][MainThread:140489457207104][task_id:default][notify.py:113][DEBUG]- 发送消息通知，消息audit_id=156
[2019-02-20 22:04:10,723][MainThread:140489457207104][task_id:default][notify.py:114][DEBUG]- 消息标题:[SQL上线申请]新的工单申请#156
通知对象：[]
消息内容：发起人：管理员
组：数据运营中心
审批流程：CTO
当前审批：CTO
工单名称：【回滚工单】原工单Id:144 ,建表
工单地址：http://139.199.0.191/workflow/156
工单详情预览：DROP TABLE `archer`.`fyt1_test`;

[2019-02-20 22:04:11,050][MainThread:140489457207104][task_id:default][sendmsg.py:132][DEBUG]- 钉钉推送成功
[2019-02-20 22:04:11,096][MainThread:140489457207104][task_id:django-q][cluster.py:333][INFO]- Processed [angel-avocado-oscar-burger]
```

尝试重启下容器关注下日志信息，确认django-q是否正常启动

后续会完善下django-q的启动管理和进程监控的内容

**Comment by sky1006** [comment]
找到错误日志了
```
2019-02-21 09:27:33,666][MainThread:140105324025664][task_id:django-q][cluster.py:305][DEBUG]- queueing from django_q:archery:q
DEBUG:django-q:queueing from django_q:archery:q
[2019-02-21 09:27:33,668][MainThread:140105324025664][task_id:django-q][cluster.py:356][INFO]- Process-1:1 processing [minnesota-oklahoma-pluto-oregon]
INFO:django-q:Process-1:1 processing [minnesota-oklahoma-pluto-oregon]
[2019-02-21 09:27:34,246][MainThread:140105324025664][task_id:django-q][cluster.py:336][ERROR]- Failed [minnesota-oklahoma-pluto-oregon] - WorkflowAudit matching query does not exist. : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/archery/sql/notify.py", line 33, in notify
    audit_info.workflow_type)
  File "/opt/archery/sql/utils/workflow_audit.py", line 358, in review_info
    audit_info = WorkflowAudit.objects.get(workflow_id=workflow_id, workflow_type=workflow_type)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
sql.models.DoesNotExist: WorkflowAudit matching query does not exist.

ERROR:django-q:Failed [minnesota-oklahoma-pluto-oregon] - WorkflowAudit matching query does not exist. : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/archery/sql/notify.py", line 33, in notify
    audit_info.workflow_type)
  File "/opt/archery/sql/utils/workflow_audit.py", line 358, in review_info
    audit_info = WorkflowAudit.objects.get(workflow_id=workflow_id, workflow_type=workflow_type)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
sql.models.DoesNotExist: WorkflowAudit matching query does not exist.
```

**Comment by hhyo** [comment]
数据库事务隔离导致的，消息发送的查询和添加不在一个事务内，消息发送去查询审核信息时，添加事务还没有commit，把消息发送放到事务提提交后调用就可以的，后面修正
