### ISSUE TITLE
/slowquery/review_history/ HTTP/1.1" 500 6753

### ISSUE THREAD

**Issue by arnoldlee128** [hhyo/Archery#571]
### 问题描述
我在点击SQL优化 - > 慢查日志时候 提示数据加载失败，请检查接口返回信息和错误日志。
在运行django 终端中输出如下：
Traceback (most recent call last):
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/Archery-1.7.3/sql/slowlog.py", line 84, in slowquery_review
    slow_sql_count = slowsql_obj.count()
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review' doesn't exist")

Internal Server Error: /slowquery/review/
Traceback (most recent call last):
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/Archery-1.7.3/sql/slowlog.py", line 84, in slowquery_review
    slow_sql_count = slowsql_obj.count()
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review' doesn't exist")
[16/Dec/2019 19:03:12] "POST /slowquery/review/ HTTP/1.1" 500 6735

### 版本信息
 - 应用版本/分支：Release v1.7.3
 - 部署方式：手工部署

**Comment by hhyo** [comment]
请查阅文档

**Comment by arnoldlee128** [comment]
> 请查阅文档

能否给确切的位置说明～ 比如说看那个位置？因为我看到数据库表确实没有mysql_slow_query_review 这个表！

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#slowquery

建议通读文档，否则会遇到各种问题

**Comment by arnoldlee128** [comment]
> https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#slowquery
> 
> 建议通读文档，否则会遇到各种问题

非常感谢～
