### ISSUE TITLE
[ 问题咨询 ]表名是mysql关键字时，查看表结构报错

### ISSUE THREAD

**Issue by baokaijian** [hhyo/Archery#578]
### 问题描述
表名叫order，申请了表权限之后查询还是没权限，看日志是表名和关键字冲突导致报错，无法查询表内容，MySQL语句执行报错，语句：show create table order;

### 版本信息
 - 部署方式：手工部署

**Comment by hhyo** [comment]
请提供具体操作、日志信息、版本信息

**Comment by baokaijian** [comment]
版本1.7.0
![image](https://user-images.githubusercontent.com/7881488/71246650-0ff18b80-2352-11ea-8537-6f21ebd6a686.png)

2019-12-20 17:30:04,445][MainThread:140494709073728][task_id:default][mysql.py:124][WARNING]- MySQL语句执行报错，语句：show create table order;，错误信息Traceback (most recent call last):
  File "/opt/Archery-1.7.0/sql/engines/mysql.py", line 113, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order' at line 1")

**Comment by hhyo** [comment]
应该是查看表结构？
可以直接查询`show create table `\`orderr\`获取相关信息。
预计下个版本修复

**Comment by baokaijian** [comment]
是的，就是查看表结构报错，导致申请了该表权限不生效

**Comment by hhyo** [comment]
和权限检验没关系，查询时使用\`\`将表框起来查询就可以

**Comment by baokaijian** [comment]
![image](https://user-images.githubusercontent.com/7881488/71249687-be98ca80-2358-11ea-8bca-2c13ece7d2f7.png)
![image](https://user-images.githubusercontent.com/7881488/71249700-c5274200-2358-11ea-9160-4fe30ec28ab3.png)
其他表申请权限都可以查询，就是表名是关键字的申请了权限查询还是提示没权限

**Comment by baokaijian** [comment]
查看表结构报错代码上加个``解决了

**Comment by hhyo** [comment]
同 #553

可升级至最新版，尝试使用goInception解析，如果不愿意升级，可以关闭inception的关键字检测，不过这样就会影响到SQL审核，还是建议升级
