### ISSUE TITLE
[ bug ]定时任务执行异常

### ISSUE THREAD

**Issue by zwunix** [hhyo/Archery#591]
定时任务执行异常，报错提示如下：

[2020-01-04 09:35:16,884][MainThread:140201753286464][task_id:django-q][cluster.py:307][DEBUG]- queueing from django_q:archery:q
[2020-01-04 09:35:16,885][MainThread:140201753286464][task_id:django-q][cluster.py:360][INFO]- Process-1:10 processing [lima-vegan-carolina-golf]
[2020-01-04 09:35:16,884][MainThread:140201753286464][task_id:django-q][tasks.py:59][INFO]- Enqueued 1
[2020-01-04 09:35:16,886][MainThread:140201753286464][task_id:django-q][tasks.py:60][DEBUG]- Pushed ('lima-vegan-carolina-golf', 'd48d5575225b44d78dc3b6d9f03dd44c')
[2020-01-04 09:35:16,886][MainThread:140201753286464][task_id:django-q][cluster.py:549][INFO]- Process-1 created a task from schedule [sqlreview-4800]
[2020-01-04 09:35:36,916][MainThread:140201753286464][task_id:default][mysql.py:132][WARNING]- MySQL语句执行报错，语句：select @@read_only;，错误信息Traceback (most recent call last):
  File "/usr/local/src/archer/Archery/sql/engines/mysql.py", line 119, in query
    conn = self.get_connection(db_name=db_name)
  File "/usr/local/src/archer/Archery/sql/engines/mysql.py", line 39, in get_connection
    connect_timeout=10)
  File "/opt/venv4archery/lib/python3.7/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host

......

[2020-01-04 09:35:37,103][MainThread:140201753286464][task_id:django-q][cluster.py:338][ERROR]- Failed [lima-vegan-carolina-golf] - list index out of range : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.7/site-packages/django_q/cluster.py", line 381, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/usr/local/src/archer/Archery/sql/utils/execute_sql.py", line 28, in execute
    return execute_engine.execute_workflow(workflow=workflow_detail)
  File "/usr/local/src/archer/Archery/sql/engines/mysql.py", line 263, in execute_workflow
    read_only = self.query(sql='select @@read_only;').rows[0][0]
IndexError: list index out of range

实际上MySQL server host 的访问是正常的。该异常是什么原因导致？

**Comment by hhyo** [comment]
可否重现？目前这边验证无法重现，应该就是在执行过程中出现无法访问mysql实例

**Comment by zwunix** [comment]
能重现。在本地环境或云上环境访问测试都是类似异常。

**Comment by zwunix** [comment]
调试了一下，在开发模式没问题，切到生产模式运行就不行。

**Comment by zwunix** [comment]
重启了qcluster可以了。
