### ISSUE TITLE
[ bug ]回滚SQL异常

### ISSUE THREAD

**Issue by Boom0910** [hhyo/Archery#592]
**版本信息**
应用版本/分支：
master最新版 1.6.7
部署方式：Docker

**数据库**
Oracle 11g

**错误信息**
[2020-01-06 16:21:31,690][DummyThread-14:140342275645512][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/sql/views.py", line 219, in rollback
    for sql in list_backup_sql:
TypeError: 'NoneType' object is not iterable

**Comment by hhyo** [comment]
并不支持非mysql的执行备份
