### ISSUE TITLE
[ bug ]

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#594]
实例管理-会话管理 查看数据库的进程状态，选择query可以显示；选择ALL就会报错。锁信息也显示不出来；一样的报错；另一个实例可以正常显示；怀疑是不是信息太多的原因。
[2020-01-08 14:59:52,035][Thread-333:139952552306432][task_id:default][mysql.py:132][WARNING]- MySQL语句执行报错，语句：select id, user, host, db, command, time, state, ifnull(info,'') as info from information_schema.processlist;，错误信息Traceback (most recent call las
t):  File "/opt/tools/Python-3.6.5/archery-1.7.3/sql/engines/mysql.py", line 121, in query
    effect_row = cursor.execute(sql)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 316, in _query
    self._do_get_result(db)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 147, in _do_get_result
    self._result = result = self._get_result()
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 349, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

锁信息：
[2020-01-08 15:00:18,543][Thread-333:139952552306432][task_id:default][mysql.py:132][WARNING]- MySQL语句执行报错，语句：
            SELECT
              rtrx.`trx_state`                                                        AS "等待的状态",
              rtrx.`trx_started`                                                      AS "等待事务开始时间",
              rtrx.`trx_wait_started`                                                 AS "等待事务等待开始时间",
              lw.`requesting_trx_id`                                                  AS "等待事务ID",
              rtrx.trx_mysql_thread_id                                                AS "等待事务线程ID",
              rtrx.`trx_query`                                                        AS "等待事务的sql",
              CONCAT(rl.`lock_mode`, '-', rl.`lock_table`, '(', rl.`lock_index`, ')') AS "等待的表信息",
              rl.`lock_id`                                                            AS "等待的锁id",
              lw.`blocking_trx_id`                                                    AS "运行的事务id",
              trx.trx_mysql_thread_id                                                 AS "运行的事务线程id",
              CONCAT(l.`lock_mode`, '-', l.`lock_table`, '(', l.`lock_index`, ')')    AS "运行的表信息",
              l.lock_id                                                               AS "运行的锁id",
              trx.`trx_state`                                                         AS "运行事务的状态",
              trx.`trx_started`                                                       AS "运行事务的时间",
              trx.`trx_wait_started`                                                  AS "运行事务的等待开始时间",
              trx.`trx_query`                                                         AS "运行事务的sql"
            FROM information_schema.`INNODB_LOCKS` rl
              , information_schema.`INNODB_LOCKS` l
              , information_schema.`INNODB_LOCK_WAITS` lw
              , information_schema.`INNODB_TRX` rtrx
              , information_schema.`INNODB_TRX` trx
            WHERE rl.`lock_id` = lw.`requested_lock_id`
                  AND l.`lock_id` = lw.`blocking_lock_id`
                  AND lw.requesting_trx_id = rtrx.trx_id
                  AND lw.blocking_trx_id = trx.trx_id;，错误信息Traceback (most recent call last):
  File "/opt/tools/Python-3.6.5/archery-1.7.3/sql/engines/mysql.py", line 121, in query
    effect_row = cursor.execute(sql)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

手动部署。版本：1.7.3

**Comment by gaoqiang-0327** [comment]
这两条语句查出来都是一百多条。

**Comment by hhyo** [comment]
数据库连接断开，确认下实例配置是中间件还是数据库

**Comment by gaoqiang-0327** [comment]
@hhyo 是阿里云ECS服务器的公网地址。是数据库的。

**Comment by hhyo** [comment]
错误都发生在cursor.execute时，说明连接是没问题，可以从几个方面排查

1. 锁信息很多，当前实例是不是负载较高，是否有pt-kill或者其他kill工具在kill连接
2. 确认max_allowed_packet值，这两个查询结果都包含当前语句信息，是否存在长SQL导致数据包超出max_allowed_packet值
3. wait_timeout值的大小，Archery获取连接会立即执行查询，如果不是特别小应该关系不大
4. 可给该实例配置查询标签，到SQL查询中执行相关语句确认是否正常

还有错误必现吗？

**Comment by gaoqiang-0327** [comment]
archery是在本地物理机部署，包括archery的数据库；有问题的数据库是阿里云的ECS服务器，因为公司网络问题，目前只能通过公网地址连接，在archery物理机上，通过mysql  -u -p -P -h阿里云公网IP。可以登录阿里云ECS服务器。在SQL查询语句中执行又报错：
[2020-01-08 16:29:06,574][Thread-10:140120199485184][task_id:default][mysql.py:132][WARNING]- MySQL语句执行报错，语句：select * from appeal_list limit 1;，错误信息Traceback (most recent call last):
  File "/opt/tools/Python-3.6.5/archery-1.7.3/sql/engines/mysql.py", line 121, in query
    effect_row = cursor.execute(sql)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/tools/Python-3.6.5/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')
怀疑是不是网络这块的问题。其他的max_allowed_packet已经调整最大了，还有时间那几个参数也不小。

**Comment by hhyo** [comment]
只能是去排查网络的原因了

**Comment by gaoqiang-0327** [comment]
外网出问题了，通了以后就可以了。
