### ISSUE TITLE
[ 问题咨询 ] 企业微信配置后，没收到通知

### ISSUE THREAD

**Issue by 0000005** [hhyo/Archery#601]
### 问题描述
我配置了相关的信息：
![image](https://user-images.githubusercontent.com/9690089/72409639-4d0a3b80-37a1-11ea-976f-d0c7c27c69aa.png)
给企业微信消息接收者配了企业微信的（userId）,审批组和资源组
![image](https://user-images.githubusercontent.com/9690089/72409687-73c87200-37a1-11ea-90b6-fc54182427db.png)
![image](https://user-images.githubusercontent.com/9690089/72409694-788d2600-37a1-11ea-97f9-b142f0636d36.png)

我提交sql查询的申请，对应的也是相应的资源组和审批组
![image](https://user-images.githubusercontent.com/9690089/72409897-fd783f80-37a1-11ea-92e3-289de3da40b3.png)

但是就是无法收到企业微信通知，后台也没有相关日志。是哪里配置还有问题吗？

### 版本信息
 - 应用版本/分支：hhyo/archery:1.7.4
 - 部署方式：Docker

**Comment by hhyo** [comment]
可以把日志等级调整为debug后重启服务，可查看更多信息，同时查看日志优先查看logs文件下的archery.log，docker日志不完整

**Comment by 0000005** [comment]
```
[2020-01-15 15:54:38,342][MainThread:140600075007808][task_id:django-q][cluster.py:338][ERROR]- Failed [query-priv-apply-7] - unsupported operand type(s) for *: 'set' and 'int' : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 381, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/archery/sql/notify.py", line 169, in notify_for_audit
    msg_sender.send_wx2user(msg_title + '\n' + msg_content, user_list)
  File "/opt/archery/common/utils/sendmsg.py", line 167, in send_wx2user
    access_token = get_wx_access_token()
  File "/opt/archery/common/utils/wx_api.py", line 29, in get_wx_access_token
    cache.set('wx_access_token', access_token, timeout={expires_in - 60})
  File "/opt/venv4archery/lib/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django_redis/client/default.py", line 129, in set
    timeout = int(timeout * 1000)
TypeError: unsupported operand type(s) for *: 'set' and 'int'
```
报错 如上

**Comment by hhyo** [comment]
踩中bug了，进容器内把`timeout={expires_in - 60}` 改成 `timeout=expires_in - 60` 重启试试，这里是复制ding_api没改掉，晚点修复

**Comment by 0000005** [comment]
嗯
按照你的改法，已经可以了

**Comment by hhyo** [comment]
我这边得找账号测试，你方便的话可以提个pr修复

**Comment by 0000005** [comment]
好的，晚点提个pr

**Comment by 0000005** [comment]
#602 pr在这里

**Comment by dmz-leon** [comment]
> 踩中bug了，进容器内把`timeout={expires_in - 60}` 改成 `timeout=expires_in - 60` 重启试试，这里是复制ding_api没改掉，晚点修复

这是指的archery容器内的配置还是其他哪个容器的配置呢？

**Comment by 0000005** [comment]
archery容器内，具体改什么文件看我的pr
