### ISSUE TITLE
[ 问题咨询 ]提交工单申请不发送钉钉消息，但是工单执行结束发送钉钉

### ISSUE THREAD

**Issue by DBAyan** [hhyo/Archery#610]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.3.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
请提供日志，同时建议升级版本

**Comment by DBAyan** [comment]
[2020-01-17 16:19:34,771][MainThread:140565036975936][task_id:default][dao.py:132][ERROR]- Traceback (most recent call last):
  File "/opt/archery/sql/utils/dao.py", line 113, in mysql_query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'xiaodai.order_record_reconciliation' doesn't exist")

[2020-01-17 16:48:03,459][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知
[2020-01-17 16:59:10,746][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知
[2020-01-17 17:04:38,799][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知
[2020-01-17 17:04:38,917][Thread-8:140564786501376][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:04:48,496][Thread-9:140564787549952][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:04:52,756][Thread-9:140564786501376][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:04:56,918][Thread-10:140564787549952][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:08:50,334][MainThread:140565036975936][task_id:default][dao.py:132][ERROR]- Traceback (most recent call last):
  File "/opt/archery/sql/utils/dao.py", line 113, in mysql_query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.

**Comment by DBAyan** [comment]
服务部署在了阿里云ecs 偶尔发送 偶尔不发送

**Comment by DBAyan** [comment]
[2020-01-17 17:19:10,319][Thread-11:140564787549952][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:23:22,505][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知
[2020-01-17 17:29:14,359][MainThread:140565036975936][task_id:django_auth_ldap][backend.py:372][DEBUG]- Authentication failed for zhangzheng: user DN/password rejected by LDAP server.
[2020-01-17 17:29:42,739][MainThread:140565036975936][task_id:django_auth_ldap][backend.py:372][DEBUG]- Authentication failed for zhangzheng: user DN/password rejected by LDAP server.
[2020-01-17 17:31:47,612][MainThread:140565036975936][task_id:django_auth_ldap][backend.py:372][DEBUG]- Authentication failed for zhangzheng: user DN/password rejected by LDAP server.
[2020-01-17 17:31:47,832][MainThread:140565036975936][task_id:django_auth_ldap][backend.py:372][DEBUG]- Authentication failed for zhangzheng: user DN/password rejected by LDAP server.
[2020-01-17 17:34:43,880][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知
[2020-01-17 17:34:43,998][Thread-11:140564786501376][task_id:default][sendmsg.py:110][DEBUG]- 钉钉推送成功
[2020-01-17 17:36:15,866][MainThread:140565036975936][task_id:default][notify.py:147][DEBUG]- 异步发送消息通知

**Comment by hhyo** [comment]
#53
具体是在1.5.3版本修复

**Comment by DBAyan** [comment]
我手动修改为rc可以吗

**Comment by hhyo** [comment]
rc也不行，根本就没到commit

**Comment by DBAyan** [comment]
感谢解答 我升级一下
