### ISSUE TITLE
[ bug ]查询语句where created_at>'2019-03-07 18:20'，时间带时分报错了

### ISSUE THREAD

**Issue by sky1006** [hhyo/Archery#62]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

**重现步骤**
简单描述问题出现场景和重现步骤

**截图**
如果可以，请提供错误信息截图方便我们定位问题
![_15519573286293](https://user-images.githubusercontent.com/7941719/53953522-80565580-410e-11e9-86d7-c5df181137ef.png)

**错误日志**
DEBUG:django-q:Pushed ('hamper-william-west-shade', 'f61a12a635944b1f89f51a94b3ba1bd6')
ERROR:default:Traceback (most recent call last):
  File "/opt/archery/sql/utils/data_masking.py", line 36, in data_masking
    table_hit_columns, hit_columns = self.analy_query_tree(query_tree, instance_name)
  File "/opt/archery/sql/utils/data_masking.py", line 154, in analy_query_tree
    query_tree_dict = json.loads(query_tree_str)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 1 column 330 (char 329)

ERROR:default:Traceback (most recent call last):
  File "/opt/archery/sql/query.py", line 530, in query
    return HttpResponse(json.dumps(masking_result), content_type='application/json')
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/__init__.py", line 382, in dumps
    return _default_encoder.encode(obj)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/encoder.py", line 286, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/encoder.py", line 368, in iterencode
    return _iterencode(o, 0)
  File "/opt/venv4archery/lib/python3.6/site-packages/simplejson/encoder.py", line 263, in default
    o.__class__.__name__)
TypeError: Object of type datetime is not JSON serializable
```
/downloads/log/archery.log
/downloads/log/soar.log
docker logs archery -f --tail=10
```

**版本信息**
 - 应用版本 1.4.1
 - 部署方式，Docker

**Comment by hhyo** [comment]
1.4.3版本已修复，docker已更新，升级请查看release说明
