### ISSUE TITLE
[ bug ] 普通用户无法进行sql优化

### ISSUE THREAD

**Issue by z790704069** [hhyo/Archery#65]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

**重现步骤**
普通用户下，SQL优化 -> 提交SQL

**错误日志**
/downloads/log/archery.log 中有如下错误信息
```
[2019-03-14 17:47:07,249][MainThread:139633946654528][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

**版本信息**
 - 部署方式，Docker部署

**Comment by z790704069** [comment]
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker.io/hhyo/archery     latest              747577413924        6 days ago          1.28 GB
docker.io/redis            5                   0f88f9be5839        9 days ago          95 MB
docker.io/mongo            3.6                 3258f7245216        9 days ago          373 MB
docker.io/mysql            5.7                 ee7cbd482336        9 days ago          372 MB
docker.io/hhyo/inception   latest              51e1968b3d59        5 weeks ago         679 MB

**Comment by hhyo** [comment]
查看文档内关于权限的部分，用户需要分配对应的执行权限才可以进行操作

**Comment by LeoQuote** [comment]
普通用户需要分配对应权限才可以， 请在admin页面给用户，或者用户所属的组分配有关sql优化的权限。

**Comment by z790704069** [comment]
got it
