### ISSUE TITLE
数据初始化时报错

### ISSUE THREAD

**Issue by kartfran** [hhyo/Archery#673]
### 问题描述
docker模式部署，在执行数据初始化时出现报错。

### 版本信息
 - 应用版本/分支：Release v1.7.7  
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/6095163/77035350-5dc86f00-69e7-11ea-85ba-bbf6945b2c1e.png)

**Comment by kartfran** [comment]
(venv) [root@localhost archery]# python3 manage.py dbshell<sql/fixtures/auth_group.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 2: Duplicate entry '1' for key 'sql_instance_tag.PRIMARY'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/client.py", line 48, in runshell
    subprocess.check_call(args)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mysql', '--user=root', '--password=Aa123456.', '--host=127.0.0.1', '--port=3306', 'mysql']' returned non-zero exit status 1.

**Comment by LeoQuote** [comment]
把 数据库drop 掉重试吧, 按文档说的要先 make migrations https://github.com/hhyo/Archery/wiki/docker

**Comment by kartfran** [comment]
(venv4archery) [root@b11fa8d0d23d archery]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/python3/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/python3/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/archery/logs/archery.log'

以上是在root权限运行

**Comment by LeoQuote** [comment]
docker怎么运行起来的？ 用了volume 吗？ docker-compose up ？

用volume可能会有permission的问题，自己查一下。

**Comment by hhyo** [comment]
实在不行所有步骤从来一次吧
