### ISSUE TITLE
1.7.8版本申请归档时报错：invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by falcondance** [hhyo/Archery#679]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

在申请归档页面，填写完配置后，提示：invalid literal for int() with base 10: ''
演示环境也是如此

### 期待结果和实际结果
期待结果：
申请成功
实际结果:
报错失败
### 截图

![image](https://user-images.githubusercontent.com/20810423/77308662-4c100000-6d36-11ea-98f0-8e679a8c600c.png)

### 错误日志
[2020-03-23 18:27:14,951][Thread-1:140033544419072][task_id:default][archiver.py:172][ERROR]- Traceback (most recent call last):
  File "/data/archery/Archery-1.7.8/sql/archiver.py", line 166, in archive_apply
    user_display=user.display,
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1367, in execute_sql
    for sql, params in self.as_sql():
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1311, in as_sql
    for obj in self.query.objs
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1311, in <listcomp>
    for obj in self.query.objs
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1310, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1251, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 788, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

### 版本信息
应用版本/分支：Archery-1.7.8

部署方式：手工部署，从1.7.1升级

**Comment by falcondance** [comment]
休眠时间时必填项导致的。。。补充下报错信息吧，或者给个默认值

**Comment by hhyo** [comment]
这种可以顺手提个pr解决它
