### ISSUE TITLE
[ 问题咨询 ] 新版本安装时候初始化数据库报错

### ISSUE THREAD

**Issue by skymoou** [hhyo/Archery#754]
### 问题描述

python3 manage.py makemigrations sql  报如下错误

django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?

### 版本信息
 - 应用版本/分支：Release v1.7.10  
 - 部署方式：手工部署

### pip3 freeze
 
[root@sqlaudit archery]# pip3 freeze
aliyun-python-sdk-core-v3==2.13.11
aliyun-python-sdk-rds==2.1.1
arrow==0.15.6
blessed==1.17.5
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
cx-Oracle==7.3.0
Django==2.2.10
django-auth-ldap==2.1.0
django-mirage-field==1.0.1
django-picklefield==2.1.1
django-q==1.0.2
django-redis==4.11.0
gevent==1.4.0
greenlet==0.4.15
gunicorn==20.0.4
idna==2.9
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
mybatis-mapper2sql==0.1.9
mysql-replication==0.21
mysqlclient==1.4.6
phoenixdb==0.7
prettytable==0.7.2
protobuf==3.12.1
psycopg2-binary==2.8.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodome==3.9.7
pyecharts==1.7.1
pymongo==3.10.1
PyMySQL==0.9.3
pyodbc==4.0.30
python-dateutil==2.8.1
python-ldap==3.2.0
pytz==2020.1
redis==3.5.2
requests==2.23.0
Schema-Object==0.5.11
Schema-Sync==0.9.7
simplejson==3.17.0
six==1.15.0
sqlparse==0.3.1
supervisor==4.1.0
tqdm==4.46.0
urllib3==1.25.9
wcwidth==0.1.9

**Comment by LeoQuote** [comment]
..... 手工部署就多学习一下, 这个错误你自己看看也能解决,另外手工部署也提供了start 脚本的, https://github.com/hhyo/Archery/blob/master/admin.sh

**Comment by skymoou** [comment]
这个脚本我看了，该安装的依赖都装了，还是不行，你可以自己下载试一下

**Comment by hhyo** [comment]
可直接进入命令行导入MySQLdb测试

docker每天都在自动构建，安装步骤不存在问题

**Comment by jimmy-bj** [comment]
我的是清净操作系统centos7-docker方式部署
执行表结构初始化
python3 manage.py makemigrations sql
报如下错误
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.1' (using password: NO)")

**Comment by jimmy-bj** [comment]
接上条，补充异常信息
(varchenv) [root@localhost Archery-1.8.0]# python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.1' (using password: NO)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 290, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/src/archery/varchenv/lib/python3.6/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.1' (using password: NO)")
