### ISSUE TITLE
[ 问题咨询 ]list index out of range

### ISSUE THREAD

**Issue by billy98** [hhyo/Archery#762]
### 问题描述
数据库实例地址变更后，普通用户查询数据就会报list index out of range，但是管理员账号是可以正常查询的。

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：手工部署

![image](https://user-images.githubusercontent.com/13307862/83473102-60e9dc00-a4bb-11ea-8a06-88a297f92b69.png)

**Comment by LeoQuote** [comment]
能不能在 demo 里复现一下这个bug ?

**Comment by billy98** [comment]
> 能不能在demo里复现一下这个bug？

因为我们的数据库做了迁移，所以链接地址变了，但是数据是一样的。所以我只改了数据库实例的链接地址，然后之前有权限的普通用户就都会报这个错。我在demo没法复现，没法迁移一个数据库。

**Comment by LeoQuote** [comment]
那发一下后台的具体trace吧.

**Comment by billy98** [comment]
[2020-06-09 16:07:47,560][DummyThread-267:139919749237320][task_id:default][query_privileges.py:84][ERROR]- 无法校验查询语句权限，rr_prod_copytrading_slave，select * from t_trades limit 100;，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 407, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 129, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
IndexError: list index out of range

**Comment by LeoQuote** [comment]
上下文还有别的 exception 吗? 看起来像是 goinception 没返回正确,

**Comment by LeoQuote** [comment]
如果你能想办法在demo上复现, 我会更方便的拿到日志.

**Comment by billy98** [comment]
[2020-06-09 16:07:45,710][DummyThread-266:139919749237320][task_id:default][goinception.py:114][WARNING]- goInception语句执行报错，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/goinception.py", line 103, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

[2020-06-09 16:07:45,710][DummyThread-266:139919749237320][task_id:default][query_privileges.py:84][ERROR]- 无法校验查询语句权限，rr_prod_copytrading_slave，select * from t_trades limit 100;，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 407, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 129, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
IndexError: list index out of range

[2020-06-09 16:07:47,559][DummyThread-267:139919749237320][task_id:default][goinception.py:114][WARNING]- goInception语句执行报错，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/goinception.py", line 103, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
[2020-06-09 16:07:47,560][DummyThread-267:139919749237320][task_id:default][query_privileges.py:84][ERROR]- 无法校验查询语句权限，rr_prod_copytrading_slave，select * from t_trades limit 100;，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 407, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 129, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
IndexError: list index out of range

**Comment by billy98** [comment]
> 如果你能想办法在demo上复现, 我会更方便的拿到日志.

你把demo的数据库实例链接换一下应该就能重现，因为我们也只是换了个链接，其他的都没变

**Comment by billy98** [comment]
还有一个点是，之前的数据库是阿里云的mysql RDS,现在是aws的mysql RDS

**Comment by LeoQuote** [comment]
```
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query') 
```

goinception 好像有点问题啊, 看看goinception 的日志吧, 能开debug 开一下debug

**Comment by billy98** [comment]
我应该怎么去看goinception，不是很懂

**Comment by billy98** [comment]
```
time="2020/06/09 15:04:26.889" level=error msg="con:4660 Error 1044: Access denied for user 'xxxxx'@'10.%' to database 'mysql'" file=session_inception.go line=2510
time="2020/06/09 15:04:26.889" level=error msg="lastCmd /*--user='xxxx';--password='xxxxxxx';--host='1.1.1.1';--port=3344;--enable-query-print;*/\n                          inception_magic_start;                          use `copytrading`;\n                          select  * from t_trades;\n                          inception_magic_commit;, runtime error: invalid memory address or nil pointer dereference, goroutine 633890 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc00ab0c000, 0xc00043dde7)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:422 +0x106\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc.func1(0xc0004f4100)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:369 +0xdd\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*PrintSets).Append(0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc0000c8640, 0x4b)\n\t/go/src/github.com/hanchuanchuan/goInception/session/inception_result.go:517 +0x26\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc0004f4100, 0x1b66440, 0xc00085f7c0, 0xc00018c141, 0x12c, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:516 +0x12a7\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc0004f4100, 0x1b66440, 0xc00085f7c0, 0xc00018c141, 0x12c, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:344 +0x320\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc00061c1b0, 0x1b66440, 0xc00085f7c0, 0xc00018c141, 0x12c, 0xc000460418, 0xc034ec64aa, 0x34ec64aa0043dc40, 0xc00043dc40, 0x42c73f)\n\t/go/src/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc00ab0c000, 0x1b66440, 0xc00085f7c0, 0xc00018c141, 0x12c, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:886 +0x80\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc00ab0c000, 0xc00018c141, 0x12d, 0x12d, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:638 +0x535\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc00ab0c000)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:467 +0x158\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc0002d1dc0, 0x1b7b460, 0xc00a3f40a8)\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:320 +0x201\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:265 +0x3ec\n" file=conn.go line=424
time="2020/06/09 16:07:45.709" level=error msg="con:4661 Error 1044: Access denied for user 'xxxx'@'10.%' to database 'mysql'" file=session_inception.go line=2510
time="2020/06/09 16:07:45.709" level=error msg="lastCmd /*--user='xxxxx';--password='xxxxxxx';--host='1.1.1.1';--port=3344;--enable-query-print;*/\n                          inception_magic_start;                          use `copytrading`;\n                          select * from t_trades limit 100;\n                          inception_magic_commit;, runtime error: invalid memory address or nil pointer dereference, goroutine 634158 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc000516000, 0xc00043dde7)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:422 +0x106\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc.func1(0xc0004f4100)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:369 +0xdd\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*PrintSets).Append(0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc0000c8640, 0x4b)\n\t/go/src/github.com/hanchuanchuan/goInception/session/inception_result.go:517 +0x26\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc0004f4100, 0x1b66440, 0xc000836040, 0xc00018c141, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:516 +0x12a7\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc0004f4100, 0x1b66440, 0xc000836040, 0xc00018c141, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:344 +0x320\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc000274810, 0x1b66440, 0xc000836040, 0xc00018c141, 0x135, 0xc000460418, 0xc02a23cc0c, 0x2a23cc0c0043dc40, 0xc00043dc40, 0x42c73f)\n\t/go/src/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc000516000, 0x1b66440, 0xc000836040, 0xc00018c141, 0x135, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:886 +0x80\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc000516000, 0xc00018c141, 0x136, 0x136, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:638 +0x535\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc000516000)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:467 +0x158\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc0002d1dc0, 0x1b7b460, 0xc00a3f40a8)\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:320 +0x201\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:265 +0x3ec\n" file=conn.go line=424
time="2020/06/09 16:07:47.558" level=error msg="con:4662 Error 1044: Access denied for user 'xxxx'@'10.%' to database 'mysql'" file=session_inception.go line=2510
time="2020/06/09 16:07:47.558" level=error msg="lastCmd /*--user='xxxx';--password='xxxxx';--host='1.1.1.1';--port=3344;--enable-query-print;*/\n                          inception_magic_start;                          use `copytrading`;\n                          select * from t_trades limit 100;\n                          inception_magic_commit;, runtime error: invalid memory address or nil pointer dereference, goroutine 634205 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc000516d00, 0xc00043dde7)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:422 +0x106\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc.func1(0xc000690c00)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:369 +0xdd\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*PrintSets).Append(0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc00003d6d0, 0x4b)\n\t/go/src/github.com/hanchuanchuan/goInception/session/inception_result.go:517 +0x26\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc000690c00, 0x1b66440, 0xc000836580, 0xc00018c501, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:516 +0x12a7\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc000690c00, 0x1b66440, 0xc000836580, 0xc00018c501, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:344 +0x320\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc00a4eeba0, 0x1b66440, 0xc000836580, 0xc00018c501, 0x135, 0xc000460418, 0xc02112050e, 0x2112050e00853c40, 0xc000853c40, 0x42c73f)\n\t/go/src/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc000516d00, 0x1b66440, 0xc000836580, 0xc00018c501, 0x135, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:886 +0x80\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc000516d00, 0xc00018c501, 0x136, 0x136, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:638 +0x535\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc000516d00)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:467 +0x158\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc0002d1dc0, 0x1b7b460, 0xc00000ea28)\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:320 +0x201\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:265 +0x3ec\n" file=conn.go line=424
```

**Comment by hhyo** [comment]
授权或者改goInception配置，它默认会去连接mysql库

**Comment by guogang1990** [comment]
我也遇到了这个问题：
![截屏2020-06-17 上午8 57 05](https://user-images.githubusercontent.com/11847516/84842765-91637580-b078-11ea-8907-d414abe9c102.png)

goinception的容器日志看到报错如下：
```
 inception_magic_start;                          use `bgw`;\n                          select * from old_payment_trans_seq;\n                          inception_magic_commit;, runtime error: invalid memory address or nil pointer dereference, goroutine 89907 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc0000f7860, 0xc00017dde7)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:422 +0x106\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc.func1(0xc00013db80)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:369 +0xdd\npanic(0x1681e80, 0x2c60d90)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/goInception/session.(*PrintSets).Append(0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc00a1bc190, 0x4f)\n\t/go/src/github.com/hanchuanchuan/goInception/session/inception_result.go:517 +0x26\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc00013db80, 0x1b663e0, 0xc00a84d380, 0xc0001d2141, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:516 +0x12a7\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc00013db80, 0x1b663e0, 0xc00a84d380, 0xc0001d2141, 0x135, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:344 +0x320\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc000a0a210, 0x1b663e0, 0xc00a84d380, 0xc0001d2141, 0x135, 0xc000448958, 0xc02a952057, 0x2a9520570017dc40, 0xc00017dc40, 0x42c73f)\n\t/go/src/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc0000f7860, 0x1b663e0, 0xc00a84d380, 0xc0001d2141, 0x135, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:886 +0x80\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc0000f7860, 0xc0001d2141, 0x136, 0x136, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:638 +0x535\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc0000f7860)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:467 +0x158\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc000368a10, 0x1b7b400, 0xc00033a000)\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:320 +0x201\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:265 +0x3ec\n" file=conn.go line=424
```

我把goinception的版本更新了一下:
docker-compose.yml里面的：image: hanchuanchuan/goinception
改成：image: hanchuanchuan/goinception:v1.2.2

后面重启一下，再去执行select脚本语句就ok了。
好像docker hub上面作者没有写latest的tag了。
@hhyo

**Comment by billy98** [comment]
如果是授权的问题，为什么管理员可以查询，就普通用户查询不了
