### ISSUE TITLE
[ 问题咨询 ]OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by hamiguas** [hhyo/Archery#795]
### 问题描述 OSError: [Errno 5] Input/output error
生产环境在执行oracle的复杂dml语句时，备份报错，但是在本机调试的时候是好的，环境一致
[Errno 5] Input/output error : Traceback (most recent call last):
File "/data/archery/sql/engines/oracle.py", line 701, in execute_workflow
print(result)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django_q/cluster.py", line 421, in worker
res = f(*task["args"], **task["kwargs"])
File "/data/archery/sql/utils/execute_sql.py", line 30, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/data/archery/sql/engines/oracle.py", line 703, in execute_workflow
print(e)
OSError: [Errno 5] Input/output error

### 版本信息
 - 应用版本/分支：Release v1.7.11 
 - 部署方式：手工部署

**Comment by michengyue** [comment]
add

**Comment by LeoQuote** [comment]
你没事 print 他干啥, 代码里都没有print, 自己开发的自己去探索

**Comment by hamiguas** [comment]
去掉print也是报错
[Errno 5] Input/output error : Traceback (most recent call last):
File "/data/archery/sql/engines/oracle.py", line 701, in execute_workflow
except Exception as e:
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django_q/cluster.py", line 421, in worker
res = f(*task["args"], **task["kwargs"])
File "/data/archery/sql/utils/execute_sql.py", line 30, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/data/archery/sql/engines/oracle.py", line 703, in execute_workflow
logger.error(f"Oracle工单备份异常，工单id：{workflow.id}， 错误信息：{traceback.format_exc()}")
OSError: [Errno 5] Input/output error
