### ISSUE TITLE
[ bug ] SQL文本过大的话，导致无法检测和提交

### ISSUE THREAD

**Issue by longqidong** [hhyo/Archery#806]
[2020-07-10 18:01:17 +0800] [3235922] [INFO] Booting worker with pid: 3235922
[2020-07-10 18:01:47 +0800] [3235922] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 266, in handle
    req = next(conn.parser)
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/http/message.py", line 186, in __init__
    super().__init__(cfg, unreader)
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/http/message.py", line 235, in parse
    self.headers = self.parse_headers(data[:idx])
  File "/u01/app/daas/venv_daas/lib/python3.6/site-packages/gunicorn/http/message.py", line 73, in parse_headers
    remote_addr = self.unreader.sock.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

SQL文本有130K左右，无法提交。

**Comment by hhyo** [comment]
检查下本地环境，目前10M以内工单提交应该是很迅速的

**Comment by longqidong** [comment]
> 检查下本地环境，目前10M以内工单提交应该是很迅速的

如果使用python manage.py runserver 的方式启动没有问题，采用gunicorn 的话则提交失败。

**Comment by longqidong** [comment]
> hmmmm 有时间还是动动小手搜一下吧
> 
> * https://stackoverflow.com/questions/58389201/gunicorn-is-failing-with-oserror-errno-107-transport-endpoint-is-not-connecte
> * [benoitc/gunicorn#1913](https://github.com/benoitc/gunicorn/issues/1913)

不止是gunicorn ，采用uwsgi也是会出现同样的问题。目前我的解决办法是，在gunicorn 前面加了一层nginx，目前已解决。
