### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by 5sdba** [hhyo/Archery#823]
### 问题描述
我添加pg实例的时候提示库不存在，我用gui工具连接测试没有问题的，想咨询下是不是哪里没有配置好
### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker
错误日志：
[root@b3769fa0c373 logs]# taif archery.log 
bash: taif: command not found
[root@b3769fa0c373 logs]# tailf archery.log 
[2020-07-20 18:08:54,911][DummyThread-262:139872069604936][task_id:default][pgsql.py:160][WARNING]- PgSQL命令执行报错，语句：SELECT datname FROM pg_database;， 错误信息：Traceback (most recent call last):
  File "/opt/archery/sql/engines/pgsql.py", line 144, in _query
    conn = self.get_connection(db_name=db_name)
  File "/opt/archery/sql/engines/pgsql.py", line 30, in get_connection
    password=self.password, dbname=db_name)
  File "/opt/venv4archery/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "db_sys" does not exist

**Comment by 5sdba** [comment]
db_sys是用户名，不是库名，我没看大设置库的地方

**Comment by LeoQuote** [comment]
重复 #813 , 请升级到最新版
