### ISSUE TITLE
[ 问题咨询 ] 设置了脱敏规则之后，一直报错：数据脱敏异常：'errmsg'

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#834]
### 问题描述
先说报错，设置了脱敏规则之后，进行sql查询报错:
前端界面报错:
```shell
数据脱敏异常：'errmsg'
```
archery.log 日志报错如下：
```python
[2020-07-25 16:15:57,952][DummyThread-26:140507007261512][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：show slave status，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

[2020-07-25 16:15:57,958][DummyThread-26:140507007261512][task_id:default][data_masking.py:37][WARNING]- 数据脱敏异常，错误信息：Traceback (most recent call last):
  File "/opt/archery/sql/utils/data_masking.py", line 32, in data_masking
    query_tree = inception_engine.query_print(instance=instance, db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/inception.py", line 173, in query_print
    raise RuntimeError(f"Inception Error: {print_info['errmsg']}")
KeyError: 'errmsg'
```

操作步骤:
#### 1. 配置Inception

配置项 | 值
| - | - 
INCEPTION | 是否切换为Inception审核
GO_INCEPTION_HOST | goInception
GO_INCEPTION_PORT | 4000
INCEPTION_HOST | inception
INCEPTION_PORT | 6669
REMOTE_BACKUP_HOST | mysql
REMOTE_BACKUP_PORT | 3306
REMOTE_BACKUP_USER | root
REMOTE_BACKUP_PASSWORD | ••••••

#### 3.配置脱敏规则
字段ID | 规则类型 | 激活状态 | INSTANCE | 字段所在库名 | 字段所在表名 | 字段名 | CREATE | TIME
| - | - | - | - | - | - | - | - | -
1 | 手机号	| 未激活 | db1 | db1	| table1 | mobile | 2020-07-25 | 16:09:54

#### 4.修改python文件
修改`pymysql/connections.py`和`pymysql/cursors.py`
修改之后的文件如下:
```python
    def _request_authentication(self):
        # https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse
        # if int(self.server_version.split('.', 1)[0]) >= 5:
        #     self.client_flag |= CLIENT.MULTI_RESULTS
        try:
            if int(self.server_version.split('.', 1)[0]) >= 5:
                self.client_flag |= CLIENT.MULTI_RESULTS
        except:
            if self.server_version.split('.', 1)[0] == 'Inception2':
                self.client_flag |= CLIENT.MULTI_RESULTS
```

```python
    def _show_warnings(self):
        if self._warnings_handled:
            return
        self._warnings_handled = True
        # if self._result and (self._result.has_next or not self._result.warning_count):
        if self._result:
            return
```

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

麻烦帮忙看下是什么问题导致的，谢谢

**Comment by ghost** [comment]
#### 脱敏规则配置
规则类型 | 规则脱敏所用的正则表达式，表达式必须分组，隐藏的组会使用****代替 | 需要隐藏的组 | 规则描述 | SYSTIME
| - | - | - | - | - 
手机号 | (.{3})(.*)(.{4}) | 2 | 无 | 2020-07-25 16:09:30

**Comment by hhyo** [comment]
非常详细的描述，看错误日志是在使用inception进行语法树打印的时候报错
建议参考文档：https://inception-document.readthedocs.io/zh_CN/latest/queryprint/ 使用测试脚本直接调用inception语法树打印查看相关输出
或者直接修改Archery相关方法，看print_info具体输出的是什么内容
https://github.com/hhyo/Archery/blob/a695ec66f15bcc9b844f7a8e9ee0c48190c244ed/sql/engines/inception.py#L156-L173

同时，docker-compose内的inception已经是修改过的版本，不需要修改pymysql的相关内容

**Comment by ghost** [comment]
#### 先说结果：问题已解决。已经通过打印日志的方式定位到问题：

实例的名称太长导致的，` ** is too long for host name (should be no longer than 60)`

#### 定位问题的操作步骤如下：

增加打印日志的代码，重新执行sql查询数据

vi /opt/archery/sql/engines/inception.py +173
```python
  def query_print(self, instance, db_name=None, sql=''):
      """
      将sql交给inception打印语法树。
      """
      sql = f"""/*--user={instance.user};--password={instance.password};--host={instance.host};
                        --port={instance.port};--enable-query-print;*/
                        inception_magic_start;\
                        use `{db_name}`;
                        {sql}
                        inception_magic_commit;"""
      print_info = self.query(db_name=db_name, sql=sql).to_dict()[0]
+     logger.error(f"打印日志: {print_info}")
      # 兼容语法错误时errlevel=0的场景
      if print_info['errlevel'] == 0 and print_info['errmsg'] == 'None':
          return json.loads(_repair_json_str(print_info['query_tree']))
      elif print_info['errlevel'] == 0 and print_info['errmsg'] == 'Global environment':
          raise SyntaxError(f"Inception Error: {print_info['query_tree']}")
      else:
          raise RuntimeError(f"Inception Error: {print_info['errmsg']}")
```

#### 日志内容输出:
```python
[2020-07-25 17:47:55,898][DummyThread-1:139952300092232][task_id:default][inception.py:167][ERROR]- 
打印日志: {
    "ID":1,
    "stage":"NONE",
    "errlevel":2,
    "stagestatus":"None",
    "errormessage":"String '*************************************************' is too long for host name (should be no longer than 60).",
    "SQL":"Global environment",
    "Affected_rows":0,
    "sequence":"None",
    "backup_dbname":"None",
    "execute_time":"0",
    "sqlsha1":"None"
}
```

#### 解决办法:
在`实例管理` - `实例列表` 将实例`HOST`字段改成ip方式连接问题就解决了

#### 后续优化建议
1. 调整 model 中`HOST`字段长度，在增加实例的时候直接报错，会直观一点

   vi /opt/archery/sql/models.py

```python
-    host = models.CharField('实例连接', max_length=200)
+    host = models.CharField('实例连接', max_length=60)
```

2. 后端将报错直接打印到日志，多记日志没有坏处～

   vi /opt/archery/sql/engines/inception.py +173

```python
 def query_print(self, instance, db_name=None, sql=''):
     """
     将sql交给inception打印语法树。
     """
     sql = f"""/*--user={instance.user};--password={instance.password};--host={instance.host};
                       --port={instance.port};--enable-query-print;*/
                       inception_magic_start;\
                       use `{db_name}`;
                       {sql}
                       inception_magic_commit;"""
     print_info = self.query(db_name=db_name, sql=sql).to_dict()[0]
     # 兼容语法错误时errlevel=0的场景
     if print_info['errlevel'] == 0 and print_info['errmsg'] == 'None':
         return json.loads(_repair_json_str(print_info['query_tree']))
     elif print_info['errlevel'] == 0 and print_info['errmsg'] == 'Global environment':
         raise SyntaxError(f"Inception Error: {print_info['query_tree']}")
     else:
+        logger.error(f"ERROR: {print_info}")
         raise RuntimeError(f"Inception Error: {print_info['errmsg']}")
```

暂时就能想到这两点，非常感谢 @hhyo 休息日回复

**Comment by LeoQuote** [comment]
非常详细，可以直接提个pr
