### ISSUE TITLE
[ bug ] 解析表出错或者表不存在，无法展示表信息

### ISSUE THREAD

**Issue by dongqianzheng** [hhyo/Archery#843]
优化工具-sql tuning 分析结果报错。

### 重现步骤
1. lower_case_table_names=0
2.创建一个表名为大写的表

### 期待结果和实际结果
实际结果:
![image](https://user-images.githubusercontent.com/26294657/89285752-8776ef80-d683-11ea-9a1e-84a74acf36e0.png)

### 错误日志
[2020-08-04 18:49:59,319][DummyThread-4:139942869869776][task_id:default][mysql.py:141][WARNING]- MySQL语句执行报错，语句：show create table `dong`;，错误信息Traceback (most recent call last):
  File "/usr/local/archery/sql/engines/mysql.py", line 130, in query
    effect_row = cursor.execute(sql)
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/python3/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'for_incep_t.dong' doesn't exist")

### 版本信息
应用版本/分支：
v1.7.4
部署方式：手工部署

是否是大小写转换，导致找不到这张表。

**Comment by hhyo** [comment]
已确认，在表解析时做了小写转换，下版本修复
