### ISSUE TITLE
[ 问题咨询 ]Archery连接ProxySQL+MGR集群执行DDL和DML

### ISSUE THREAD

**Issue by zsp108** [hhyo/Archery#854]
### 问题描述
Archery连接ProxySQL+MGR集群提交DDL和DML工单正常，Archery的实例配置连接端口设置的是proxySQL的地址端口，然后执行的时候返回报错，报错日志在下面

SELECT @@global.read_only;这个操作我从proxy登录执行是可以的

我的MGR是三个节点的多主模式，ProxySQL写是往一个节点写，其他两个节点负责读，读写不能再同一个节点上
从报错信息上看好像是查询read_only这个操作发送到了只读节点上，查询到了read_only，然后返回操作失败？

![image](https://user-images.githubusercontent.com/31213457/91157068-7441c780-e6f7-11ea-9cd6-5929176c88e7.png)

/logs/archery.log
[2020-08-25 17:19:49,389][MainThread:140058530666304][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：SELECT @@global.read_only;，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (9006, 'ProxySQL Error: connection is locked to hostgroup 1 but trying to reach hostgroup 2')

[2020-08-25 17:19:49,435][MainThread:140058530666304][task_id:django-q][cluster.py:338][ERROR]- Failed [sqlreview-execute-21] - list index out of range : Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 381, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/opt/archery/sql/utils/execute_sql.py", line 35, in execute
    return execute_engine.execute_workflow(workflow=workflow_detail)
  File "/opt/archery/sql/engines/mysql.py", line 292, in execute_workflow
    read_only = self.query(sql='SELECT @@global.read_only;').rows[0][0]
IndexError: list index out of range

### 版本信息
 - 应用版本/分支： releasev1.7.12
 - 部署方式：Docker部署，移植到k8s部署

**Comment by LeoQuote** [comment]
相关issue ： https://github.com/hhyo/Archery/issues/409

但是这个问题应该早已修复

**Comment by LeoQuote** [comment]
有条件的话可以先升级goinception看看

**Comment by hhyo** [comment]
`MySQLdb._exceptions.OperationalError: (9006, 'ProxySQL Error:connection is locked to hostgroup 1 but trying to reach hostgroup 2 ')`

执行语句判断目标库是否只读时出错了，可以在proxysql中创建一个路由规则，识别到平台执行用户时强制路由到主库

**Comment by zsp108** [comment]
收到，我先把这些试下看看是否可以，感谢大佬们的解答

**Comment by zsp108** [comment]
> `MySQLdb._exceptions.OperationalError: (9006, 'ProxySQL Error:connection is locked to hostgroup 1 but trying to reach hostgroup 2 ')`
> 
> 执行语句判断目标库是否只读时出错了，可以在proxysql中创建一个路由规则，识别到平台执行用户时强制路由到主库

感谢大佬，我目前是创建了一个特定账号给Archery使用，设置路由规则这个账号的所有请求都发送到主节点上执行，解决了执行报错的问题，后面出现了备份报错，这个看之前@LeoQuote 大佬给的issues应该是inception不支持proxysql的备份，不支持现在是否解决了？

**Comment by hhyo** [comment]
备份都是通过dump binlog去逆向生成，proxysql不支持 dump binlog，所以目前应该不会支持备份，可以在工单提交时关闭备份

**Comment by zsp108** [comment]
> 备份都是通过dump binlog去逆向生成，proxysql不支持 dump binlog，所以目前应该不会支持备份，可以在工单提交时关闭备份

收到，感谢解答
