### ISSUE TITLE
[ 问题咨询 ] 查询只能看表结构，无法查询，Error 无法校验查询语句权限，请联系管理员，错误信息：connect() argument 1 must be str, not None

### ISSUE THREAD

**Issue by hailianghe** [hhyo/Archery#860]
### 问题描述
刚开始还能查询，后来分配到默认的rd权限组，不能查询，只能看表结构；
已经看issue里面有相同的问题，也是1.7.12的docker,他是配置了inception解决的，但是我们不需要脱敏，所以停止了inception；
尝试过：启动inception, 重启docker，增加移除实例，都没解决

archery报错：
```

[2020-08-30 12:38:35,493][DummyThread-4:139918017665608][task_id:default][query_privileges.py:84][ERROR]- 无法校验查询语句权限，公司内网dba_01数据库，select
  *
from
  t_cxy_statistical_study;，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 407, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 137, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[1]
  File "/opt/archery/sql/engines/goinception.py", line 108, in query
    conn = self.get_connection()
  File "/opt/archery/sql/engines/goinception.py", line 35, in get_connection
    connect_timeout=10)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 1 must be str, not None
```

### 版本信息
 - 应用版本/分支：Release v1.7.12
 - 部署方式：Docker

报错截图：
![image](https://user-images.githubusercontent.com/29939806/91651401-e121dc80-eabe-11ea-8e4f-05fece047357.png)
![image](https://user-images.githubusercontent.com/29939806/91651406-eaab4480-eabe-11ea-9bde-a48eaac2df6c.png)
![image](https://user-images.githubusercontent.com/29939806/91651419-044c8c00-eabf-11ea-87ef-bf021ce44fdc.png)

**Comment by hhyo** [comment]
查询权限检验依赖goinception，检查相关配置

**Comment by hailianghe** [comment]
把goinception的容器删除，重新docker-compose up -d 创建一个goinception就好了

**Comment by hailianghe** [comment]
第二次部署了下， 发现是“配置项”里面要配置下goinception的Host和port
![image](https://user-images.githubusercontent.com/29939806/91661864-34247f80-eb11-11ea-93d9-922f284001a1.png)
