### ISSUE TITLE
[ LDAP用户登录Archery权限组bug ]

### ISSUE THREAD

**Issue by dbayangzhengyu** [hhyo/Archery#882]
### 重现步骤
背景：
  Archery版本：1.7.13
  接入了LDAP登录
  新用户默认权限组为QA组，QA组权限如下：
permission_id
 73
 74
 75
 77
 78
 79
 89
 95
 96
 99
104
107

### 期待结果和实际结果
期待结果：
LDAP用户第二次登录，拥有第一次登出的权限，而不是连QA权限都没有了

实际结果:

第二次登录后，该用户啥权限都没有了，在后台发现居然登录的时候会去删除该用户的所有权限组

**Comment by LeoQuote** [comment]
用户只有在第一次登录的时候会初始化权限，你可以去看代码逻辑，一直没有变化的。

你说的后台发现登录会删权限，是怎么样得出的这个结论？有没有日志或者截图？

**Comment by dbayangzhengyu** [comment]
是我自己测试的。因为第二次登录后没权限组了，sql_users_groups表该用户的权限也没有记录了，所以我自己测试了一下，第二次登录前，我开启一个会话事务，把这个用户的那行权限记录给锁住：SELECT * from sql_users_groups WHERE users_id =49 for update;  然后不提交， 再去网页登录，发现登录卡住 ，我去数据库show full processlist。发现delete卡住了。见下图：
![image](https://user-images.githubusercontent.com/71441380/93469066-88f23380-f922-11ea-97e7-5f0a0c631f16.png)

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/737c70c1bafa75ac19d55b45b414df4ebaddb9ae/archery/settings.py#L194

可以确认下和这个配置是否相关

**Comment by dbayangzhengyu** [comment]
刚刚修改后，重启了 一下。不管用。现在又改回来。这边把他要删除的权限记录行锁住，然后登录测试用户。看到日志下面日志：
Traceback (most recent call last):
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/archery/common/auth.py", line 115, in authenticate_entry
    result = new_auth.authenticate()
  File "/data/archery/common/auth.py", line 97, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/data/archery/common/auth.py", line 51, in challenge
    user = authenticate(username=username, password=password)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 151, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 209, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 353, in authenticate
    self._get_or_create_user()
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 635, in _get_or_create_user
    self._mirror_groups()
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 785, in _mirror_groups
    self._user.groups.set(existing_groups + new_groups)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 996, in set
    self.remove(*old_ids)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 950, in remove
    self._remove_items(self.source_field_name, self.target_field_name, *objs)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 1129, in _remove_items
    self.through._default_manager.using(db).filter(filters).delete()
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/deletion.py", line 294, in delete
    count = qs._raw_delete(using=self.using)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/query.py", line 725, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1205, **_'Lock wait timeout exceeded; try restarting transaction_**')

**Comment by hhyo** [comment]
贴一下ldap的配置，看起来是开启了从ldap同步组信息，所以每次登录会更新权限组

**Comment by dbayangzhengyu** [comment]
这边已经排查到问题。settings.py的AUTH_LDAP_MIRROR_GROUPS = True  ----这个参数设定了会每次去LDAP拉去用户的权限。把这个参数注释即可。

**Comment by dbayangzhengyu** [comment]
感谢各位的解答 ，辛苦了 谢谢
