### ISSUE TITLE
dashboard界面显示：Server Error (500)

### ISSUE THREAD

**Issue by zenglingmin168** [hhyo/Archery#916]
### 问题描述
登录archery之后，dashboard界面显示：Server Error (500)，请问这个是什么原因，是因为还没有数据吗？

### 版本信息
 - 应用版本/分支：Release v1.7.13.5  
 - 部署方式：Docker

请大佬指教

**Comment by LeoQuote** [comment]
有日志才能知道具体是什么原因, 给一下日志吧

**Comment by zenglingmin168** [comment]
[2020-10-14 13:08:31,158][DummyThread-2:140276950328136][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review_history' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/common/dashboard.py", line 113, in pyecharts
    data = chart_dao.slow_query_count_by_db_by_user(1)
  File "/opt/archery/common/utils/chart_dao.py", line 162, in slow_query_count_by_db_by_user
    return self.__query(sql)
  File "/opt/archery/common/utils/chart_dao.py", line 12, in __query
    cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review_history' doesn't exist")

**Comment by zenglingmin168** [comment]
这个是日志哈，大佬

**Comment by zenglingmin168** [comment]
大佬，日志如下：
[2020-10-14 13:08:31,158][DummyThread-2:140276950328136][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
&nbsp;&nbsp;&nbsp; return self.cursor.execute(sql)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
&nbsp;&nbsp;&nbsp; return self.cursor.execute(query, args)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
&nbsp;&nbsp;&nbsp; res = self._query(query)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
&nbsp;&nbsp;&nbsp; db.query(q)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
&nbsp;&nbsp;&nbsp; _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review_history' doesn't exist")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
&nbsp;&nbsp;&nbsp; response = wrapped_callback(request, *callback_args, **callback_kwargs)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
&nbsp;&nbsp;&nbsp; return view_func(request, *args, **kwargs)
&nbsp; File "/opt/archery/common/dashboard.py", line 113, in pyecharts
&nbsp;&nbsp;&nbsp; data = chart_dao.slow_query_count_by_db_by_user(1)
&nbsp; File "/opt/archery/common/utils/chart_dao.py", line 162, in slow_query_count_by_db_by_user
&nbsp;&nbsp;&nbsp; return self.__query(sql)
&nbsp; File "/opt/archery/common/utils/chart_dao.py", line 12, in __query
&nbsp;&nbsp;&nbsp; cursor.execute(sql)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
&nbsp;&nbsp;&nbsp; return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
&nbsp;&nbsp;&nbsp; return executor(sql, params, many, context)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
&nbsp;&nbsp;&nbsp; return self.cursor.execute(sql, params)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
&nbsp;&nbsp;&nbsp; raise dj_exc_value.with_traceback(traceback) from exc_value
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
&nbsp;&nbsp;&nbsp; return self.cursor.execute(sql)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
&nbsp;&nbsp;&nbsp; return self.cursor.execute(query, args)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
&nbsp;&nbsp;&nbsp; res = self._query(query)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
&nbsp;&nbsp;&nbsp; db.query(q)
&nbsp; File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
&nbsp;&nbsp;&nbsp; _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'archery.mysql_slow_query_review_history' doesn't exist")






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 中午12:25
收件人:&nbsp;"hhyo/Archery"<Archery@noreply.github.com&gt;;
抄送:&nbsp;"向往美好明天"<3108775440@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hhyo/Archery] dashboard界面显示：Server Error (500) (#916)





 
有日志才能知道具体是什么原因, 给一下日志吧

**Comment by LeoQuote** [comment]
看起来是表没建好, 跑一下 sql 语句建一下表吧

**Comment by zenglingmin168** [comment]
数据库是要单独安装吗？有一条sql报下面这个错：
(venv4archery) [root@4146077a2dd3 archery]# python3 manage.py dbshell<sql/fixtures/auth_group.sql
Warning: Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 2: Duplicate entry '1' for key 'PRIMARY'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/client.py", line 48, in runshell
    subprocess.check_call(args)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mysql', '--user=root', '--password=123456', '--host=mysql', '--port=3306', 'archery']' returned non-zero exit status 1.

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/docker#%E5%90%AF%E5%8A%A8 按照里的先操作一下吧

**Comment by zenglingmin168** [comment]
好的，大佬，我重新搞下，谢啦！另外我按文档配的ldap怎么不生效呢？求大佬指点迷津




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:26
收件人:&nbsp;"hhyo/Archery"<Archery@noreply.github.com&gt;;
抄送:&nbsp;"向往美好明天"<3108775440@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hhyo/Archery] dashboard界面显示：Server Error (500) (#916)





 
https://github.com/hhyo/archery/wiki/docker#%E5%90%AF%E5%8A%A8 按照里的先操作一下吧
