### ISSUE TITLE
[ 功能建议 ]阿里云RDS进程状态500错误，原因是RequestServiceOfCloudDBA接口取消了

### ISSUE THREAD

**Issue by wineejam** [hhyo/Archery#935]
### 目前遇到的问题/使用障碍
阿里云RDS会话管理中的 进程状态 报500错误，咨询了阿里云客服是说RequestServiceOfCloudDBA这个接口取消了

`[2020-10-21 17:40:46,730][DummyThread-24:140228630950216][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/data/Archery/Archery-1.7.13/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/Archery/Archery-1.7.13/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/Archery/Archery-1.7.13/sql/db_diagnostic.py", line 30, in process
    result = aliyun_process_status(request)
  File "/data/Archery/Archery-1.7.13/sql/aliyun_rds.py", line 102, in process_status
    'ShowProcessList', {"Language": "zh", "Command": command_type})
  File "/data/Archery/Archery-1.7.13/common/utils/aliyun_sdk.py", line 74, in RequestServiceOfCloudDBA
    result = self.request_api(request, values)
  File "/data/Archery/Archery-1.7.13/common/utils/aliyun_sdk.py", line 30, in request_api
    result = self.clt.do_action_with_exception(request)
  File "/data/Archery/Archery-1.7.13/venv/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 467, in do_action_with_exception
    raise exception
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 500 Error:InternalError The request processing has failed due to some unknown error, exception or failure. RequestID: A8BB1C52-C205-4F37-AA34-3D5BA002224B`

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
🤦🏿‍♀️ 阿里云真坑，这才几年接口就下了

**Comment by blookerP** [comment]
可以降级aliyunsdkrds版本，或者将老版本的RequestServiceOfCloudDBA.py复制到新版本sdk里来

**Comment by hhyo** [comment]
#912

**Comment by wineejam** [comment]
![image](https://user-images.githubusercontent.com/8789004/98313661-4c33e600-200f-11eb-88f3-43edb037af2b.png)
@hhyo  按照 #912 的说明是说 aliyun-python-sdk-rds是要小于2.1.9，但是我一直是按照requirements.txt中安装的依赖库，而且我也检查了版本是2.1.1
pip list |grep aliyun
aliyun-python-sdk-core-v3 2.13.11
aliyun-python-sdk-rds     2.1.1
但是现在rds的会话管理还是报错，错误信息依旧是500
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 500 Error:InternalError The request processing has failed due to some unknown error, exception or failure. RequestID: 2E537E9D-0E0E-4491-AE3D-00068CA5E34A

**Comment by LeoQuote** [comment]
阿里云有什么替代方案提供吗?
