### ISSUE TITLE
> 查看：[danfengcao/binlog2sql#66](https://github.com/danfengcao/binlog2sql/issues/66)

### ISSUE THREAD

**Issue by mawenbin666** [hhyo/Archery#945]
> 查看：[danfengcao/binlog2sql#66](https://github.com/danfengcao/binlog2sql/issues/66)
> 安装PyMySQL==0.9.3即可：
> 步骤：
> docker exec -it archery bash
> source /opt/venv4archery/bin/activate
> pip list
> PyMySQL 0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip uninstall PyMySQL
> Found existing installation: PyMySQL 0.10.0
> Uninstalling PyMySQL-0.10.0:
> Would remove:
> /opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/*
> /opt/venv4archery/lib/python3.6/site-packages/pymysql/*
> Proceed (y/n)? y
> Successfully uninstalled PyMySQL-0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip install PyMySQL==0.9.3
> Collecting PyMySQL==0.9.3
> Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
> |████████████████████████████████| 47 kB 38 kB/s
> Installing collected packages: PyMySQL
> Successfully installed PyMySQL-0.9.3
> (venv4archery) [root@00111dac9d42 archery]# pip list
> PyMySQL 0.9.3
> (venv4archery) [root@00111dac9d42 archery]# exit
> exit
> [root@mytestuse ~]# docker stop archery
> archery
> [root@mytestuse ~]# docker start archery
> archery
> [root@mytestuse ~]#
> 解析binlog：
> ![image](https://user-images.githubusercontent.com/71009460/95848085-286ae080-0d80-11eb-9e34-b652834fe30a.png)

卸载 PyMySQL 0.10.0的时候报错，具体信息如下：
```
venv4archery) [root@ded5340b4336 archery]# pip uninstall PyMySQL
Found existing installation: PyMySQL 0.10.0
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/commands/uninstall.py", line 79,in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 535,in from_dist
    for path in uninstallation_paths(dist):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 67, in unique
    for item in fn(*args, **kw):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 85, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/RECORD'
```

_Originally posted by @mawenbin666 in https://github.com/hhyo/Archery/issues/899#issuecomment-717711785_

**Comment by LeoQuote** [comment]
你在说什么? 组织清楚再提 issue 好吧, 你做了什么, 为什么要做, 预期是什么, 实际是什么?

**Comment by hhyo** [comment]
1.8.0已处理
