### ISSUE TITLE
[ 问题咨询 ] 数据库无法正常查询 提示脱敏异常

### ISSUE THREAD

**Issue by ZhouMin-** [hhyo/Archery#948]
### 问题描述
数据库可以正常连接查询无法查询
![图片](https://user-images.githubusercontent.com/10267039/97542651-18026900-1a02-11eb-9d45-58147976251d.png)

报错信息:
![图片](https://user-images.githubusercontent.com/10267039/97542898-77f90f80-1a02-11eb-90f5-1f0e068e3c7d.png)

[2020-10-29 16:17:45,074][DummyThread-7:139798316215880][task_id:default][inception.py:181][INFO]- {'ID': 1, 'statement': 'select * from area limit 100', 'errlevel': 1, 'query_tree': 'None', 'errmsg': "Identifier 'work' is keyword in MySQL.\n"}

[2020-10-29 16:17:45,074][DummyThread-7:139798316215880][task_id:default][inception.py:182][ERROR]- 打印日志: {'ID': 1, 'statement': 'select * from area limit 100', 'errlevel': 1, 'query_tree': 'None', 'errmsg': "Identifier 'work' is keyword in MySQL.\n"}
[2020-10-29 16:17:45,075][DummyThread-7:139798316215880][task_id:default][data_masking.py:37][WARNING]- 数据脱敏异常，错误信息：Traceback (most recent call last):

  File "/septnet/data/Archery-1.7.8/sql/utils/data_masking.py", line 32, in data_masking
    query_tree = inception_engine.query_print(instance=instance, db_name=db_name, sql=sql)
  File "/septnet/data/Archery-1.7.8/sql/engines/inception.py", line 189, in query_print
    raise RuntimeError(f"Inception Error: {print_info['errmsg']}")
RuntimeError: Inception Error: Identifier 'work' is keyword in MySQL.

Inception 错误如何解决

### 版本信息
 - 应用版本/分支：Release v1.7.8  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
#145 
脱敏是有限的功能，可以配置inception相关参数，或者关闭脱敏校验

**Comment by hhyo** [comment]
https://github.com/hhyo/inception/issues/12
