### ISSUE TITLE
[ bug ]查询报错“Object of type memoryview is not JSON serializable”

### ISSUE THREAD

**Issue by niuxz** [hhyo/Archery#971]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 错误日志

<!--请务必查看相关错误日志并贴出（这很关键），查看方式
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/wwwroot/Archery/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/Archery/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/wwwroot/Archery/Archery/sql/query.py", line 175, in query
    return HttpResponse(json.dumps(result, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/__init__.py", line 412, in dumps
    **kw).encode(obj)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/data/wwwroot/Archery/Archery/common/utils/extend_json_encoder.py", line 51, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type memoryview is not JSON serializable

[2020-11-19 10:30:46,446][DummyThread-34:140505328194376][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/data/wwwroot/Archery/Archery/common/utils/extend_json_encoder.py", line 49, in default
    return convert(obj)
  File "/usr/lib64/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/data/wwwroot/Archery/Archery/common/utils/extend_json_encoder.py", line 11, in convert
    raise TypeError('can not convert type')
TypeError: can not convert type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/wwwroot/Archery/venv4archery/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/Archery/venv4archery/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/wwwroot/Archery/Archery/sql/query.py", line 175, in query
    return HttpResponse(json.dumps(result, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/__init__.py", line 412, in dumps
    **kw).encode(obj)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/data/wwwroot/Archery/Archery/common/utils/extend_json_encoder.py", line 51, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/data/wwwroot/Archery/venv4archery/lib64/python3.6/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type memoryview is not JSON serializable


-->
### 版本信息
应用版本/分支：1.6.2

部署方式：手工部署

数据库：PG 11
<!--
一般建议使用release版本，其他都是非稳定版本
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署
-->

**Comment by learn0208** [comment]
@niuxz 目前我的临时解决方式如下：
common/utils/extend_json_encoder.py  新增代码

```python
@convert.register(memoryview)
def _(o):
    return str(o)
```

**Comment by hhyo** [comment]
考虑参考这个修改，如果验证正常欢迎提交pr

https://github.com/getredash/redash/blob/1b8ff8e810aaa81c8aa8f28aef9e1ca3632b8521/redash/utils/__init__.py#L97

**Comment by learn0208** [comment]
对于memoryview这种数据类型，这边跟研发讨论过，如果不能解码至源字符串，是没有意义的事情。
解码至源字符串，会有一些问题，比如编码字符集的问题。所以这边放弃了这个解码的动作。
研发有需要会自己去解码
