### ISSUE TITLE
[ bug ]使用最新1.8.0版本，集成ldap后，ldap账号和本地账号均不能正常登陆

### ISSUE THREAD

**Issue by LaiJingli** [hhyo/Archery#978]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1、下载1.8.0版本release包  https://github.com/hhyo/archery/releases/
2、按照文档 https://github.com/hhyo/Archery/wiki 中docker安装方式安装
3、启动后，创建的本地账号可以正常登陆系统
4、配置开启 ldap
# vi /opt/archery/archery/settings.py
# LDAP
#ENABLE_LDAP = False
ENABLE_LDAP = True
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch

    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
        'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
    )

    AUTH_LDAP_SERVER_URI = "ldap://10.0.0.1:389"
    AUTH_LDAP_BING_DN = 'cn=manager,dc=xxx,dc=com'
    AUTH_LDAP_BING_PASSWORD = 'xxx'
    AUTH_LDAP_USER_DN_TEMPLATE = "cn=%(user)s,ou=users,dc=xxx,dc=com"
    AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "cn",
        "display": "displayname",
        "email": "mail"
    }

5、重启docker restart archery

6、本地用户和ldap账号均不能正常登陆，提示Internal Server Error

### 期待结果和实际结果
期待结果：
本地用户和ldap账号均能正常登陆

实际结果:
本地用户和ldap账号均不能正常登陆，提示Internal Server Error

### 错误日志
1、本地账号登陆时报错 logs/archery.log：
[2020-12-01 18:17:15,048][ThreadPoolExecutor-0_0:140662623364864][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 330, in thread_handler
    raise exc_info[1]
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/opt/archery/common/auth.py", line 108, in authenticate_entry
    result = new_auth.authenticate()
  File "/opt/archery/common/auth.py", line 92, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/opt/archery/common/auth.py", line 51, in challenge
    user = authenticate(username=username, password=password)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 65, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 26, in _get_backends
    backend = load_backend(backend_path)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 20, in load_backend
    return import_string(path)()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/venv4archery/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 66, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/opt/venv4archery/lib/python3.8/site-packages/django/utils/__init__.py)

2、ldap用户登录时报错 logs/archery.log：
[2020-12-01 18:40:09,296][ThreadPoolExecutor-0_0:140527453898496][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/auth.py", line 64, in authenticate
    user = Users.objects.get(username=username)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
sql.models.Users.DoesNotExist: Users matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 330, in thread_handler
    raise exc_info[1]
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/opt/archery/common/auth.py", line 108, in authenticate_entry
    result = new_auth.authenticate()
  File "/opt/archery/common/auth.py", line 66, in authenticate
    authenticated_user = self.challenge(username=username, password=password)
  File "/opt/archery/common/auth.py", line 51, in challenge
    user = authenticate(username=username, password=password)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 65, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 26, in _get_backends
    backend = load_backend(backend_path)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 20, in load_backend
    return import_string(path)()
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/venv4archery/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 66, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/opt/venv4archery/lib/python3.8/site-packages/django/utils/__init__.py)

### 版本信息
应用版本/分支：
Release v1.8.0
部署方式：Docker、手工部署
Docker

**Comment by hhyo** [comment]
看错误是django_auth_ldap的版本过于陈旧了，是否有人工覆盖安装过依赖包？
可以访问类似接口查看下系统依赖的版本信息
https://demo.archerydms.com/api/debug

**Comment by LaiJingli** [comment]
> 看错误是django_auth_ldap的版本过于陈旧了，是否有人工覆盖安装过依赖包？
> 可以访问类似接口查看下系统依赖的版本信息
> https://demo.archerydms.com/api/debug

谢谢~

可能是这个原因，开始我设置的ldap不起作用，后来按照https://blog.csdn.net/zhengchaooo/article/details/108361300 安装了一下依赖包，我看这个文档是2020-09-02发布的，而archery 1.8.0是2020年11月01日发布的，这个文档应该不适合1.8.0版本的archery。

现在解决了：删除老镜像，重新拉取就ok了。
