### ISSUE TITLE
[ 问题咨询 ] 无法连接开启了强制SSL的mysql数据库，报错【无法连接实例,(9002, 'SSL connection is required. Please specify SSL options and retry.')】

### ISSUE THREAD

**Issue by whiletrue57** [hhyo/Archery#988]
### 问题描述
我添加了mysql实例，实例上开启了强制SSl，在web页面的实例列表中，点击【测试】，会提示【无法连接实例,(9002, 'SSL connection is required. Please specify SSL options and retry.')】，我尝试在settings.py添加了【'ssl': {'ca': '/opt/archery/certs/DigiCertGlobalRootCA.crt.pem'}】，但是无效，看后台未产生日志。请问这个如何解决呢，谢谢大佬们
![图片](https://user-images.githubusercontent.com/10782374/101859217-371a1c00-3ba6-11eb-8f9e-18d1617f2c43.png)

还有一个地方是，【SQL上线】【提交SQL】在选择实例列表后，提示以上报错
![图片](https://user-images.githubusercontent.com/10782374/101859796-5cf3f080-3ba7-11eb-8943-f3739d1794c7.png)
后台日志如下：
[2020-12-11 11:50:30,344][ThreadPoolExecutor-0_0:140300872365824][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：show databases，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 146, in query
    conn = self.get_connection(db_name=db_name)
  File "/opt/archery/sql/engines/mysql.py", line 43, in get_connection
    self.conn = MySQLdb.connect(host=self.host, port=self.port, user=self.user, passwd=self.password,
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (9002, 'SSL connection is required. Please specify SSL options and retry.')

### 版本信息
 - 应用版本/分支：v1.8.0 
 - 部署方式：docker

**Comment by hhyo** [comment]
#918 
感谢反馈，目前不支持ssl连接，这个改动略大，暂时不做处理

**Comment by whiletrue57** [comment]
您好，我暂时的解决的方法是，修改/opt/archery/sql/engines/mysql.py文件，get_connection函数中添加ssl={'ca':'/opt/archery/DigiCertGlobalRootCA.crt.pem'}

![图片](https://user-images.githubusercontent.com/10782374/102072611-13bcce80-3e3d-11eb-8b26-1870d59c22ca.png)
