### ISSUE TITLE
redis smembers 报错

### ISSUE THREAD

**Issue by dba3306** [hhyo/Archery#992]
### 问题描述
redis smembers 报错
```
TypeError: can not convert type
```
### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker
### 日志查看和问题排查
```
[2020-12-17 17:53:25,200][ThreadPoolExecutor-0_0:139732539578112][task_id:default][exception_logging_middleware.py:11][ERROR]- Traceback (most recent call last):
  File "/opt/archery/common/utils/extend_json_encoder.py", line 49, in default
    return convert(obj)
  File "/usr/local/python3/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 11, in convert
    raise TypeError('can not convert type')
TypeError: can not convert type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 330, in thread_handler
    raise exc_info[1]
  File "/opt/venv4archery/lib/python3.8/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/archery/sql/query.py", line 175, in query
    return HttpResponse(json.dumps(result, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/opt/archery/common/utils/extend_json_encoder.py", line 51, in default
    return super(ExtendJSONEncoderFTime, self).default(obj)
  File "/opt/venv4archery/lib/python3.8/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type set is not JSON serializable
```

**Comment by hhyo** [comment]
#1142 #1156
